davidmigloz/langchain_dart

packages/langchain/lib/src/documents/loaders/base.dart, packages/langchain/lib/src/documents/transformers/text_splitters/character.dart, packages/langchain/lib/src/documents/transformers/text_splitters/recursive_character.dart, packages/langchain/lib/src/documents/transformers/text_splitters/text_splitter.dart, packages/langchain/lib/src/documents/transformers/text_splitters/text_splitters.dart, packages/langchain/lib/src/documents/transformers/text_splitters/utils.dart, packages/langchain/lib/src/documents/transformers/transformers.dart, packages/langchain/test/documents/transformers/text_splitters/character_test.dart, packages/langchain/test/documents/transformers/text_splitters/recursive_character_test.dart, packages/langchain/test/documents/transformers/text_splitters/utils_test.dart
=> feat: Add support for RecursiveCharacterTextSplitter

packages/langchain/lib/src/documents/transformers/text_splitters/character.dart, packages/langchain/lib/src/documents/transformers/text_splitters/code.dart, packages/langchain/lib/src/documents/transformers/text_splitters/recursive_character.dart, packages/langchain/lib/src/documents/transformers/text_splitters/text_splitter.dart, packages/langchain/lib/src/documents/transformers/text_splitters/text_splitters.dart, packages/langchain/lib/src/documents/transformers/text_splitters/utils.dart, packages/langchain/test/documents/transformers/text_splitters/code_test.dart
=> feat: Add support for CodeTextSplitter

packages/langchain/lib/src/documents/loaders/json.dart, packages/langchain/lib/src/documents/loaders/loaders.dart, packages/langchain/lib/src/documents/loaders/text.dart, packages/langchain/pubspec.yaml, packages/langchain/test/documents/loaders/assets/example.json, packages/langchain/test/documents/loaders/assets/example_1.json, packages/langchain/test/documents/loaders/assets/example_2.json, packages/langchain/test/documents/loaders/json.dart
Adds JSON Loader support
- Issue: #72 
- Dependencies: json_path
- A unit test has been provided
- General: @davidmigloz
=> Issue #72 - JSON Loader

packages/langchain/test/memory/stores/message/in_memory_test.dart
I pulled the project and there were missing some test from when changing to queue #81 
Maintainer: @davidmigloz
=> tests: missing remove last and remove first tests

packages/langchain_openai/lib/src/agents/functions.dart
=> fix(agents): FunctionChatMessage not saved properly in memory

packages/langchain/lib/src/model_io/prompts/chat_prompt.dart
=> docs(prompts): Fix typo in MessagePlaceholder API docs

packages/langchain_openai/lib/src/agents/functions.dart
=> docs(agents): Add example of using memory in OpenAIFunctionsAgent

packages/langchain/lib/src/chains/base.dart, packages/langchain/lib/src/chains/retrieval_qa.dart, packages/langchain/lib/src/utils/exception.dart
=> docs(chains): Improve RetrievalQAChain API documentation

packages/langchain_google/lib/langchain_google.dart, packages/langchain_google/lib/src/clients/clients.dart, packages/langchain_google/lib/src/clients/vertex_ai/models/chat.dart, packages/langchain_google/lib/src/clients/vertex_ai/models/model.dart, packages/langchain_google/lib/src/clients/vertex_ai/models/models.dart, packages/langchain_google/lib/src/clients/vertex_ai/models/text.dart, packages/langchain_google/lib/src/clients/vertex_ai/models/text_embeddings.dart, packages/langchain_google/lib/src/clients/vertex_ai/vertex_ai.dart, packages/langchain_google/lib/src/clients/vertex_ai/vertex_ai_model_garden_client.dart, packages/langchain_google/pubspec.yaml, packages/langchain_google/test/clients/vertex_ai/models/chat_test.dart, packages/langchain_google/test/clients/vertex_ai/models/text_embeddings_test.dart, packages/langchain_google/test/clients/vertex_ai/models/text_test.dart, packages/langchain_google/test/clients/vertex_ai/vertex_ai_model_garden_test.dart
Adds support for PaLM API:
- `text-bison`: Optimized for performing natural language tasks, such as classification, summarization, extraction, content creation, and ideation.
- `chat-bison`: Optimized for multi-turn chat, where the model keeps track of previous messages in the chat and uses it as context for generating new responses.
- `textembedding-gecko`: Generates text embeddings for a given text. You can use embeddings for tasks like semantic search, recommendation, classification, and outlier detection.
=> feat: Add GCP Vertex AI Model Garden API client 

packages/langchain/lib/src/chains/combine_documents/map_reduce.dart, packages/langchain/lib/src/chains/combine_documents/stuff.dart, packages/langchain/lib/src/model_io/chat_models/models/models.dart, packages/langchain/lib/src/model_io/language_models/models/models.dart, packages/langchain/lib/src/model_io/llms/models/models.dart, packages/langchain_google/lib/src/llms/llms.dart, packages/langchain_google/lib/src/llms/models/mappers.dart, packages/langchain_google/lib/src/llms/models/models.dart, packages/langchain_google/lib/src/llms/vertex_ai.dart, packages/langchain_google/pubspec.yaml, packages/langchain_google/test/llms/vertex_ai_test.dart, packages/langchain_openai/lib/src/chat_models/models/models.dart, packages/langchain_openai/lib/src/llms/mappers.dart, packages/langchain_openai/lib/src/llms/models/models.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/vertex_ai/README.md, packages/vertex_ai/lib/src/gen_ai/gen_ai_client.dart
=> feat(llms): Integrate Google Vertex AI PaLM Text model

packages/langchain/lib/src/model_io/chat_models/models/models.dart, packages/langchain_google/lib/langchain_google.dart, packages/langchain_google/lib/src/chat_models/chat_models.dart, packages/langchain_google/lib/src/chat_models/models/mappers.dart, packages/langchain_google/lib/src/chat_models/models/models.dart, packages/langchain_google/lib/src/chat_models/vertex_ai.dart, packages/langchain_google/lib/src/llms/models/mappers.dart, packages/langchain_google/test/chat_models/vertex_ai_test.dart, packages/langchain_google/test/llms/vertex_ai_test.dart, packages/langchain_openai/lib/src/chat_models/models/mappers.dart, packages/langchain_openai/lib/src/chat_models/openai.dart, packages/langchain_openai/lib/src/llms/models/mappers.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/langchain_openai/test/chat_models/openai_test.dart, packages/vertex_ai/lib/src/gen_ai/mappers/text_chat.dart
=> feat(chat-models): Integrate Google Vertex AI PaLM Chat Model

README.md, packages/langchain_google/README.md, packages/langchain_google/lib/langchain_google.dart, packages/langchain_google/lib/src/chat_models/vertex_ai.dart, packages/langchain_google/lib/src/embeddings/embeddings.dart, packages/langchain_google/lib/src/embeddings/vertex_ai.dart, packages/langchain_google/lib/src/llms/vertex_ai.dart, packages/langchain_google/test/chat_models/vertex_ai_test.dart, packages/langchain_google/test/embeddings/vertex_ai_test.dart, packages/langchain_google/test/llms/vertex_ai_test.dart, packages/langchain_google/test/utils/auth.dart, packages/langchain_openai/README.md, packages/langchain_openai/lib/src/chains/qa_with_sources.dart, packages/vertex_ai/README.md
=> feat(embeddings): Integrate Google Vertex AI PaLM Embeddings

packages/langchain/lib/src/documents/models/models.dart, packages/langchain/lib/src/documents/vector_stores/base.dart, packages/langchain/lib/src/documents/vector_stores/memory.dart, packages/langchain_google/lib/langchain_google.dart, packages/langchain_google/lib/src/llms/vertex_ai.dart, packages/langchain_google/lib/src/vector_stores/matching_engine.dart, packages/langchain_google/lib/src/vector_stores/vector_stores.dart, packages/langchain_google/pubspec.yaml, packages/langchain_google/test/utils/auth.dart, packages/langchain_google/test/vector_stores/matching_engine.dart, packages/vertex_ai/test/matching_engine/maching_engine_client_test.dart
=> feat(stores): Integrate Vertex AI Matching Engine vector store

packages/langchain/lib/src/documents/embeddings/cache.dart, packages/langchain/lib/src/documents/embeddings/embeddings.dart, packages/langchain/lib/src/storage/encoder_backed.dart, packages/langchain/test/documents/embeddings/cache.dart, packages/langchain/test/storage/encoder_backed.dart
https://python.langchain.com/docs/modules/data_connection/caching_embeddings
=> feat(embeddings): Add support for CacheBackedEmbeddings

packages/langchain/lib/src/chains/question_answering/stuff.dart, packages/langchain/lib/src/documents/retrievers/vector_store.dart, packages/langchain/lib/src/documents/vector_stores/base.dart, packages/langchain/lib/src/documents/vector_stores/memory.dart, packages/langchain/lib/src/documents/vector_stores/models/models.dart, packages/langchain/test/chains/retrieval_qa_test.dart, packages/langchain/test/documents/vector_stores/memory_test.dart, packages/langchain_google/lib/src/vector_stores/matching_engine.dart, packages/langchain_google/test/vector_stores/matching_engine.dart
- Made VectorStoreSearchType a sealed class (similarity and mrr)
- Each can have specific configuration (e.g. scoreThreshold)
- Implemented scoreThreshold in MemoryVectorStore and VertexAIMatchingEngine
=> feat(vector-stores): Allow to pass vector search config 

packages/langchain/lib/src/documents/vector_stores/models/models.dart, packages/langchain_google/lib/src/vector_stores/matching_engine.dart, packages/langchain_google/lib/src/vector_stores/models/mappers.dart, packages/langchain_google/lib/src/vector_stores/models/models.dart, packages/langchain_google/lib/src/vector_stores/vector_stores.dart, packages/langchain_google/test/vector_stores/matching_engine.dart
https://cloud.google.com/vertex-ai/docs/matching-engine/filtering
=> feat(vector-stores): Support filtering in VertexAI Matching Engine

packages/chromadb/.gitignore, packages/chromadb/CHANGELOG.md, packages/chromadb/LICENSE, packages/chromadb/README.md, packages/chromadb/analysis_options.yaml, packages/chromadb/example/chromadb_example.dart, packages/chromadb/lib/chromadb.dart, packages/chromadb/lib/src/chroma_client.dart, packages/chromadb/lib/src/collection.dart, packages/chromadb/lib/src/embeddings/embedding_function.dart, packages/chromadb/lib/src/generated/client.dart, packages/chromadb/lib/src/generated/schema/add_embedding.dart, packages/chromadb/lib/src/generated/schema/collection_type.dart, packages/chromadb/lib/src/generated/schema/create_collection.dart, packages/chromadb/lib/src/generated/schema/delete_embedding.dart, packages/chromadb/lib/src/generated/schema/get_embedding.dart, packages/chromadb/lib/src/generated/schema/get_response.dart, packages/chromadb/lib/src/generated/schema/http_validation_error.dart, packages/chromadb/lib/src/generated/schema/query_embedding.dart, packages/chromadb/lib/src/generated/schema/query_response.dart, packages/chromadb/lib/src/generated/schema/schema.dart, packages/chromadb/lib/src/generated/schema/schema.freezed.dart, packages/chromadb/lib/src/generated/schema/schema.g.dart, packages/chromadb/lib/src/generated/schema/update_collection.dart, packages/chromadb/lib/src/generated/schema/update_embedding.dart, packages/chromadb/lib/src/generated/schema/validation_error.dart, packages/chromadb/oas/main.dart, packages/chromadb/oas/openapi.json, packages/chromadb/pubspec.yaml, packages/chromadb/test/chroma_client_test.dart
=> feat(chromadb): Add Chroma embedding database API client

packages/chromadb/lib/src/generated/client.dart, packages/chromadb/pubspec.yaml
@davidmigloz update chroma client using the latest [openapi_spec](https://pub.dev/packages/openapi_spec) package release.
I did not see a docker compose file for `chromadb` so I did not run the tests. If you can execute those, that would be great!
=> Update generated Chroma API client

.github/workflows/test.yaml, packages/langchain_pinecone/lib/langchain_pinecone.dart, packages/langchain_pinecone/lib/src/vector_stores/models/mappers.dart, packages/langchain_pinecone/lib/src/vector_stores/models/models.dart, packages/langchain_pinecone/lib/src/vector_stores/pinecone.dart, packages/langchain_pinecone/lib/src/vector_stores/vector_stores.dart, packages/langchain_pinecone/pubspec.yaml, packages/langchain_pinecone/test/vector_stores/pinecone_test.dart
=> Add support for Pinecone VectorStore

packages/langchain_openai/lib/src/chat_models/models/models.dart, packages/langchain_openai/lib/src/chat_models/openai.dart, packages/langchain_openai/lib/src/llms/models/models.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/langchain_openai/test/chat_models/openai_test.dart, packages/langchain_openai/test/llms/openai_test.dart
=> feat(llms): Add ability to specify user in OpenAI and ChatOpenAI

packages/langchain/lib/src/documents/loaders/json.dart, packages/langchain/lib/src/documents/loaders/text.dart, packages/langchain_chroma/test/vector_stores/assets/example.txt, packages/langchain_chroma/test/vector_stores/chroma_test.dart
`lastModified` field used to be a `DateTime` object but that was causing issues with vector stores that only supports primitive types. Now it is an integer that represents the number of milliseconds since the "Unix epoch" 1970-01-01T00:00:00Z (UTC).
=> fix(loaders)!: Change loaders lastModified metadata field to integer

packages/openai_dart/lib/src/generated/schema/create_embedding_response.dart, packages/openai_dart/lib/src/generated/schema/embedding.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/test/openai_client_embeddings_test.dart
=> feat(openai_dart): Support new embeddings API functionality

packages/openai_dart/lib/src/generated/schema/fine_tuning_job.dart, packages/openai_dart/lib/src/generated/schema/fine_tuning_job_event.dart, packages/openai_dart/lib/src/generated/schema/list_fine_tuning_job_events_response.dart, packages/openai_dart/lib/src/generated/schema/list_paginated_fine_tuning_jobs_response.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/test/openai_client_fine_tuning_test.dart
=> feat(openai_dart): Support new fine-tunning API functionality

packages/openai_dart/lib/src/generated/schema/list_models_response.dart, packages/openai_dart/lib/src/generated/schema/model.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/pubspec.yaml, packages/openai_dart/test/openai_client_models_test.dart
=> feat(openai_dart): Support new models API functionality

packages/langchain_openai/lib/src/chat_models/models/mappers.dart, packages/langchain_openai/lib/src/chat_models/models/models.dart, packages/langchain_openai/lib/src/chat_models/openai.dart, packages/langchain_openai/lib/src/llms/models/mappers.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/langchain_openai/test/chat_models/openai_test.dart, packages/langchain_openai/test/llms/openai_test.dart
Seed example:
```dart
final prompt = PromptValue.string('How are you?');
final llm = ChatOpenAI(
temperature: 0,
seed: 9999,
);
final res1 = await llm.invoke(prompt);
expect(res1.generations, hasLength(1));
final generation1 = res1.generations.first;
final res2 = await llm.invoke(prompt);
expect(res2.generations, hasLength(1));
final generation2 = res2.generations.first;
expect(
res1.modelOutput?['system_fingerprint'],
res2.modelOutput?['system_fingerprint'],
);
expect(generation1.output, generation2.output);
```
JSON mode example:
```dart
final prompt = PromptValue.chat([
ChatMessage.system(
"Extract the 'name' and 'origin' of any companies mentioned in the "
'following statement. Return a JSON list.',
),
ChatMessage.human(
'Google was founded in the USA, while …
```
=> feat(chat-models): Support seed, system_fingerprint and JSON Mode in ChatOpenAI

packages/openai_dart/README.md, packages/openai_dart/lib/src/generated/schema/create_chat_completion_request.dart, packages/openai_dart/lib/src/generated/schema/create_completion_request.dart, packages/openai_dart/oas/openapi_curated.yaml
=> fix(openai_dart): Fix integer overflow when targeting web

packages/chromadb/build.yaml, packages/chromadb/lib/chromadb.dart, packages/chromadb/lib/src/chroma_client.dart, packages/chromadb/lib/src/collection.dart, packages/chromadb/lib/src/embeddings/embedding_function.dart, packages/chromadb/lib/src/generated/client.dart, packages/chromadb/lib/src/generated/schema/add_embedding.dart, packages/chromadb/lib/src/generated/schema/create_collection.dart, packages/chromadb/lib/src/generated/schema/create_database.dart, packages/chromadb/lib/src/generated/schema/create_tenant.dart, packages/chromadb/lib/src/generated/schema/database_type.dart, packages/chromadb/lib/src/generated/schema/delete_embedding.dart, packages/chromadb/lib/src/generated/schema/get_embedding.dart, packages/chromadb/lib/src/generated/schema/get_response.dart, packages/chromadb/lib/src/generated/schema/query_embedding.dart, packages/chromadb/lib/src/generated/schema/query_response.dart, packages/chromadb/lib/src/generated/schema/schema.dart, packages/chromadb/lib/src/generated/schema/schema.freezed.dart, packages/chromadb/lib/src/generated/schema/schema.g.dart, packages/chromadb/lib/src/generated/schema/tenant_type.dart, packages/chromadb/lib/src/generated/schema/update_collection.dart, packages/chromadb/lib/src/generated/schema/update_embedding.dart, packages/chromadb/lib/src/generated/schema/validation_error.dart, packages/chromadb/lib/src/loaders/data_loader.dart, packages/chromadb/oas/main.dart, packages/chromadb/oas/openapi_curated.json, packages/chromadb/oas/openapi_official.json, packages/chromadb/pubspec.yaml, packages/chromadb/test/chroma_client_test.dart
New features:
- tenants and databases support
- global headers (e.g. for authentication)
- multi-modal support
=> feat(chromadb): Multi-modal and tenants support

docs/modules/retrieval/vector_stores/integrations/chroma.md, packages/langchain_chroma/lib/src/vector_stores/chroma.dart
- tenants and databases support
- global headers (e.g. for authentication)
=> feat(vector-stores): Chroma databases, tenants and global headers support

packages/langchain_openai/lib/src/chat_models/openai.dart, packages/langchain_openai/lib/src/embeddings/openai.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/openai_dart/README.md, packages/openai_dart/lib/src/client.dart, packages/openai_dart/lib/src/generated/client.dart, packages/openai_dart/pubspec.yaml
https://learn.microsoft.com/en-us/azure/ai-services/openai/overview
=> feat(openai_dart): Add Azure OpenAI API support

docs/modules/agents/agent_types/openai_functions_agent.md, examples/docs_examples/bin/modules/agents/agent_types/openai_functions_agent.dart, packages/langchain/lib/src/agents/agent.dart, packages/langchain/lib/src/agents/executors.dart, packages/langchain/lib/src/agents/models/models.dart, packages/langchain/test/agents/executors_test.dart, packages/langchain/test/model_io/output_parsers/functions_test.dart, packages/langchain_openai/lib/src/agents/agents.dart, packages/langchain_openai/lib/src/agents/functions.dart, packages/langchain_openai/test/agents/functions_test.dart
Example OpenAIFunctions agent:
```dart
final openaiApiKey = Platform.environment['OPENAI_API_KEY'];
final prompt = ChatPromptTemplate.fromPromptMessages([
SystemChatMessagePromptTemplate.fromTemplate(
'You are a helpful assistant',
),
HumanChatMessagePromptTemplate.fromTemplate('{input}'),
const MessagesPlaceholder(variableName: 'agent_scratchpad'),
]);
final tool = CalculatorTool();
final model = ChatOpenAI(
temperature: 0,
).bind(ChatOpenAIOptions(functions: [tool.toChatFunction()]));
const outputParser = OpenAIFunctionsAgentOutputParser();
List<ChatMessage> buildScratchpad(final List<AgentStep> intermediateSteps) {
return intermediateSteps
.map((final s) {
return s.action.messageLog +
[
ChatMessage.function(
name: s.action.tool,
content: s.observation,
),
];
}) …
```
=> feat(agents): Support implementing custom agents using LCEL

packages/openai_dart/lib/src/generated/client.dart, packages/openai_dart/pubspec.yaml
Fixes #233 (ref https://github.com/tazatechnology/openapi_spec/issues/43)
=> fix(openai_dart): Decode JSON responses as UTF-8

packages/chromadb/lib/src/chroma_client.dart, packages/chromadb/lib/src/generated/client.dart, packages/chromadb/lib/src/generated/schema/add_embedding.dart, packages/chromadb/lib/src/generated/schema/collection_type.dart, packages/chromadb/lib/src/generated/schema/create_collection.dart, packages/chromadb/lib/src/generated/schema/create_database.dart, packages/chromadb/lib/src/generated/schema/create_tenant.dart, packages/chromadb/lib/src/generated/schema/database_type.dart, packages/chromadb/lib/src/generated/schema/delete_embedding.dart, packages/chromadb/lib/src/generated/schema/get_embedding.dart, packages/chromadb/lib/src/generated/schema/get_response.dart, packages/chromadb/lib/src/generated/schema/http_validation_error.dart, packages/chromadb/lib/src/generated/schema/query_embedding.dart, packages/chromadb/lib/src/generated/schema/query_response.dart, packages/chromadb/lib/src/generated/schema/schema.dart, packages/chromadb/lib/src/generated/schema/tenant_type.dart, packages/chromadb/lib/src/generated/schema/update_collection.dart, packages/chromadb/lib/src/generated/schema/update_embedding.dart, packages/chromadb/lib/src/generated/schema/validation_error.dart, packages/chromadb/pubspec.yaml
Related to #233 (ref https://github.com/tazatechnology/openapi_spec/issues/43)
=> fix(chromadb): Decode JSON responses as UTF-8 (#234)

docs/modules/chains/chains.md, docs/modules/chains/foundational/llm.md, docs/modules/chains/getting_started.md, docs/modules/chains/how_to/custom_chain.md, docs/modules/memory/memory.md, docs/modules/model_io/models/llms/how_to/token_usage_tracking.md, docs/modules/model_io/prompts/prompt_templates/custom_prompt_template.md, packages/langchain/lib/src/model_io/chat_models/fake.dart, packages/langchain/lib/src/model_io/language_models/base.dart, packages/langchain/lib/src/model_io/llms/fake.dart, packages/langchain/test/core/runnable/binding_test.dart, packages/langchain_google/lib/src/chat_models/vertex_ai.dart, packages/langchain_google/lib/src/llms/vertex_ai.dart, packages/langchain_openai/example/langchain_openai_example.dart, packages/langchain_openai/lib/langchain_openai.dart, packages/langchain_openai/lib/src/chat_models/openai.dart, packages/langchain_openai/lib/src/llms/models/models.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/langchain_openai/test/agents/tools/dall_e_test.dart, packages/langchain_openai/test/llms/openai_test.dart
Until now, `OpenAI` completions wrapper used to accept the completions request parameters (e.g. `temperature`) in the constructor as parameters. Like:
```
final llm = OpenAI(apiKey: openaiApiKey, temperature: 0.9);
```
This was not ideal, as it was not possible to change the parameters after the object was created. So, for example, if you wanted to change the temperature, you had to create a new instance.
Now, all the completions request parameters are part of the `OpenAIOptions` class.
When you create an instance of `OpenAI`, you can define the `defaultOptions` that will be used for all the completions requests.
If you want to change the parameters for a specific request, you can pass the desired `OpenAIOptions` when making the request. The options passed in the request will override the …
=> feat(llms)!: Move all model config options to OpenAIOptions

packages/langchain_mistralai/.gitignore, packages/langchain_mistralai/CHANGELOG.md, packages/langchain_mistralai/LICENSE, packages/langchain_mistralai/README.md, packages/langchain_mistralai/analysis_options.yaml, packages/langchain_mistralai/lib/langchain_mistralai.dart, packages/langchain_mistralai/lib/src/chat_models/chat_mistralai.dart, packages/langchain_mistralai/lib/src/chat_models/chat_models.dart, packages/langchain_mistralai/lib/src/chat_models/models/mappers.dart, packages/langchain_mistralai/lib/src/chat_models/models/models.dart, packages/langchain_mistralai/lib/src/embeddings/embeddings.dart, packages/langchain_mistralai/lib/src/embeddings/mistralai_embeddings.dart, packages/langchain_mistralai/pubspec.yaml, packages/langchain_mistralai/pubspec_overrides.yaml, packages/langchain_mistralai/test/chat_models/chat_mistralai_test.dart, packages/langchain_mistralai/test/embeddings/mistralai_embeddings_test.dart, packages/langchain_ollama/lib/src/chat_models/models/models.dart, packages/langchain_openai/lib/src/chat_models/models/mappers.dart
https://mistral.ai/news/la-plateforme/
=> feat(chat-models): Add support for ChatMistralAI wrapper

packages/langchain_mistralai/lib/src/embeddings/embeddings.dart, packages/langchain_mistralai/lib/src/embeddings/mistralai_embeddings.dart, packages/langchain_mistralai/test/embeddings/mistralai_embeddings_test.dart
https://mistral.ai/news/la-plateforme/
```dart
final embeddings = MistralAIEmbeddings(apiKey: 'apiKey');
const text = 'This is a test document.';
final res = await embeddings.embedQuery(text);
final res = await embeddings.embedDocuments([text]);
```
=> feat(embeddings): Add support for MistralAIEmbeddings (#254)

packages/langchain/lib/src/memory/memory.dart, packages/langchain/test/memory/buffer_test.dart, packages/langchain/test/memory/buffer_window_test.dart, packages/langchain/test/memory/simple_test.dart, packages/langchain/test/memory/summary_test.dart, packages/langchain/test/memory/token_buffer_test.dart
ConversationSummaryMemory class was not exported
=> fix(memory): Export ConversationSummaryMemory

packages/openai_dart/README.md, packages/openai_dart/lib/src/generated/schema/chat_completion_response_choice.dart, packages/openai_dart/lib/src/generated/schema/chat_completion_stream_response_choice.dart, packages/openai_dart/lib/src/generated/schema/create_chat_completion_response.dart, packages/openai_dart/lib/src/generated/schema/create_chat_completion_stream_response.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/test/openai_client_chat_test.dart
=> feat(openai_dart): Support OpenRouter API

packages/openai_dart/README.md, packages/openai_dart/lib/src/generated/schema/create_chat_completion_stream_response.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml
https://docs.together.ai/docs/openai-api-compatibility
=> feat(openai_dart): Support Together AI API

packages/openai_dart/README.md, packages/openai_dart/lib/src/generated/schema/create_chat_completion_response.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/test/openai_client_chat_test.dart
https://docs.endpoints.anyscale.com/
=> feat: Support Anyscale API in openai_dart client

packages/vertex_ai/README.md, packages/vertex_ai/lib/src/gen_ai/apis/text.dart, packages/vertex_ai/lib/src/gen_ai/apis/text_chat.dart, packages/vertex_ai/lib/src/gen_ai/mappers/mappers.dart, packages/vertex_ai/lib/src/gen_ai/mappers/model.dart, packages/vertex_ai/lib/src/gen_ai/models/model.dart, packages/vertex_ai/test/gen_ai/gen_ai_client_test.dart
https://cloud.google.com/vertex-ai/docs/generative-ai/get-token-count
=> feat: Add count tokens method to vertex_ai client

packages/openai_dart/lib/src/generated/schema/create_embedding_request.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/oas/openapi_official.yaml, packages/openai_dart/test/openai_client_embeddings_test.dart
https://openai.com/blog/new-embedding-models-and-api-updates#new-embedding-models-with-lower-pricing
=> feat: Add text-embedding-3-small and text-embedding-3-large in model catalog

packages/openai_dart/lib/src/generated/schema/create_embedding_request.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/oas/openapi_official.yaml, packages/openai_dart/test/openai_client_embeddings_test.dart
https://openai.com/blog/new-embedding-models-and-api-updates#native-support-for-shortening-embeddings
=> feat: Add support for shortening embeddings

packages/langchain_openai/lib/src/chat_models/models/models.dart, packages/langchain_openai/lib/src/embeddings/openai.dart, packages/langchain_openai/lib/src/llms/models/models.dart, packages/langchain_openai/test/embeddings/openai_embeddings_test.dart
https://openai.com/blog/new-embedding-models-and-api-updates#native-support-for-shortening-embeddings
=> feat: Add support for shortening embeddings in OpenAIEmbeddings

packages/langchain_community/.gitignore, packages/langchain_community/CHANGELOG.md, packages/langchain_community/LICENSE, packages/langchain_community/README.md, packages/langchain_community/analysis_options.yaml, packages/langchain_community/example/langchain_community_example.dart, packages/langchain_community/lib/langchain_community.dart, packages/langchain_community/pubspec.yaml
=> feat: Bootstrap langchain_community package

docs/modules/model_io/models/chat_models/integrations/ollama.md, examples/docs_examples/bin/modules/model_io/models/chat_models/integrations/ollama.dart, packages/langchain/README.md, packages/langchain_openai/test/chat_models/open_router_test.dart
=> docs: Add RAG example using OllamaEmbeddings and ChatOllama (#337)

docs/expression_language/cookbook/retrieval.md, examples/docs_examples/bin/expression_language/cookbook/retrieval.dart, packages/langchain_core/lib/src/runnables/map.dart, packages/langchain_core/lib/src/runnables/sequence.dart
https://discord.com/channels/1123158322812555295/1226924464545992884/1226924464545992884
=> fix: Stream has already been listened to exception in RunnableMap

analysis_options.yaml, docs/_sidebar.md, docs/expression_language/cookbook/routing.md, docs/expression_language/interface.md, examples/browser_summarizer/pubspec.lock, examples/docs_examples/bin/expression_language/cookbook/routing.dart, examples/docs_examples/pubspec.lock, examples/hello_world_backend/pubspec.lock, examples/hello_world_cli/pubspec.lock, examples/hello_world_flutter/pubspec.lock, examples/vertex_ai_matching_engine_setup/pubspec.lock, packages/langchain/lib/langchain.dart, packages/langchain/lib/src/utils/utils.dart, packages/langchain/lib/src/vector_stores/memory.dart, packages/langchain/test/vector_stores/memory_test.dart, packages/langchain_core/lib/src/documents/document.dart, packages/langchain_core/lib/src/runnables/router.dart, packages/langchain_core/lib/src/runnables/runnable.dart, packages/langchain_core/lib/src/runnables/runnables.dart, packages/langchain_core/lib/src/utils/reduce.dart, packages/langchain_core/lib/src/utils/similarity.dart, packages/langchain_core/lib/src/utils/utils.dart, packages/langchain_core/test/runnables/router_test.dart, packages/langchain_core/test/utils/reduce_test.dart, packages/langchain_core/test/utils/similarity_test.dart, packages/openai_dart/oas/main.dart
=> Add support for RunnableRouter (#169)

packages/openai_dart/lib/src/generated/schema/run_step_delta_step_details_tool_calls.dart, packages/openai_dart/lib/src/generated/schema/run_step_details_tool_calls.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml
Ref: https://github.com/davidmigloz/langchain_dart/issues/401#issuecomment-2101737765
=> fix: RunStepDetailsToolCalls deserialization in Assistants API v2

packages/openai_dart/lib/src/generated/schema/message_content_text_annotations_file_citation.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml
=> fix: Make quote nullable in MessageContentTextAnnotationsFileCitation

packages/ollama_dart/README.md, packages/ollama_dart/lib/src/generated/client.dart, packages/ollama_dart/oas/ollama-curated.yaml
Resolves https://github.com/davidmigloz/langchain_dart/pull/411#issuecomment-2118900456
=> fix: digest path param in Ollama blob endpoints

packages/openai_dart/README.md, packages/openai_dart/lib/src/generated/schema/create_chat_completion_stream_response.dart, packages/openai_dart/lib/src/generated/schema/function_object.dart, packages/openai_dart/lib/src/generated/schema/function_parameters.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/oas/openapi_official.yaml
Resolves https://github.com/davidmigloz/langchain_dart/issues/442
=> feat: Support FastChat OpenAI-compatible API

packages/ollama_dart/lib/src/client.dart
Refs: 
- https://discord.com/channels/1123158322812555295/1244582758421102594/1244582758421102594
- https://github.com/cloudflare/cloudflared/issues/1095
=> feat: Support buffered stream responses in ollama_dart

packages/langgraph/.gitignore, packages/langgraph/CHANGELOG.md, packages/langgraph/LICENSE, packages/langgraph/README.md, packages/langgraph/analysis_options.yaml, packages/langgraph/example/langgraph_example.dart, packages/langgraph/lib/langgraph.dart, packages/langgraph/pubspec.yaml
Relates to https://github.com/davidmigloz/langchain_dart/issues/287
=> feat: Bootstrap `langgraph` package

packages/tavily_dart/README.md, packages/tavily_dart/build.yaml, packages/tavily_dart/example/tavily_dart_example.dart, packages/tavily_dart/lib/src/generated/client.dart, packages/tavily_dart/lib/src/generated/schema/schema.dart, packages/tavily_dart/lib/src/generated/schema/schema.freezed.dart, packages/tavily_dart/lib/src/generated/schema/schema.g.dart, packages/tavily_dart/lib/src/generated/schema/search_request.dart, packages/tavily_dart/lib/src/generated/schema/search_response.dart, packages/tavily_dart/lib/src/generated/schema/search_result.dart, packages/tavily_dart/lib/tavily_dart.dart, packages/tavily_dart/oas/main.dart, packages/tavily_dart/oas/tavily_openapi.yaml, packages/tavily_dart/pubspec.yaml, packages/tavily_dart/test/tavily_test.dart
=> feat: Implement tavily_dart, a Dart client for Tavily API

melos.yaml, packages/langchain_firebase/example/macos/Flutter/GeneratedPluginRegistrant.swift, packages/langchain_firebase/example/pubspec.lock, packages/langchain_firebase/example/pubspec.yaml, packages/langchain_firebase/lib/src/chat_models/vertex_ai/mappers.dart, packages/langchain_firebase/pubspec.lock, packages/langchain_firebase/pubspec.yaml
```dart
final chatModel = ChatFirebaseVertexAI();
final res = chatModel.invoke(...);
final usage = res.usage;
print(usage.promptTokens);
print(usage.candidatesTokenCount);
print(usage.totalTokenCount);
```
=> feat: Add support for usage metadata in ChatFirebaseVertexAI

packages/langchain_firebase/lib/src/chat_models/vertex_ai/chat_firebase_vertex_ai.dart
Passing the tools in the actual generate request is now supported:
https://github.com/firebase/flutterfire/pull/12824
=> refactor: Simplify how tools are passed to the internal Firebase client

melos.yaml, packages/langchain_google/lib/src/chat_models/google_ai/chat_google_generative_ai.dart, packages/langchain_google/lib/src/chat_models/google_ai/mappers.dart, packages/langchain_google/lib/src/chat_models/google_ai/types.dart, packages/langchain_google/pubspec.yaml
Ref: https://ai.google.dev/gemini-api/docs/api-overview#json
=> feat: Support response MIME type and schema in ChatGoogleGenerativeAI

packages/langchain_firebase/lib/src/chat_models/vertex_ai/chat_firebase_vertex_ai.dart, packages/langchain_firebase/lib/src/chat_models/vertex_ai/mappers.dart, packages/langchain_firebase/lib/src/chat_models/vertex_ai/types.dart
Ref: https://ai.google.dev/gemini-api/docs/api-overview#json
=> feat: Support response MIME type in ChatFirebaseVertexAI (#461)

packages/anthropic_sdk_dart/lib/src/generated/schema/block.dart, packages/anthropic_sdk_dart/lib/src/generated/schema/create_message_request.dart, packages/anthropic_sdk_dart/lib/src/generated/schema/message.dart, packages/anthropic_sdk_dart/lib/src/generated/schema/schema.freezed.dart, packages/anthropic_sdk_dart/lib/src/generated/schema/schema.g.dart, packages/anthropic_sdk_dart/oas/main.dart
- `ModelEnumeration` -> `ModelCatalog`
- `ModelString` -> `ModelId`
- `MessageContentString` -> `MessageContentText`
- `MessageContentListBlock` -> `MessageContentBlocks`
- `ToolResultBlockContentString` -> `ToolResultBlockContentText`
- `ToolResultBlockContentListBlock` -> `ToolResultBlockContentBlocks`
=> refactor: Improve schemas names in anthropic_sdk_dart

packages/langchain_ollama/lib/src/chat_models/types.dart, packages/ollama_dart/lib/src/generated/schema/request_options.dart, packages/ollama_dart/lib/src/generated/schema/schema.freezed.dart, packages/ollama_dart/oas/ollama-curated.yaml
=> docs: Update Ollama request options default values in API docs

packages/openai_dart/lib/src/client.dart
Feature request from https://discord.com/channels/1123158322812555295/1123158323496235030/1264869981171089448
=> feat: Allow to customize OpenAI-Beta header in openai_dart

docs/expression_language/primitives/router.md, docs/modules/model_io/models/chat_models/integrations/ollama.md, docs/modules/model_io/models/llms/integrations/ollama.md, docs/modules/retrieval/text_embedding/integrations/ollama.md, docs/modules/retrieval/vector_stores/integrations/objectbox.md, examples/docs_examples/bin/expression_language/cookbook/routing.dart, examples/docs_examples/bin/modules/model_io/models/chat_models/integrations/ollama.dart, examples/docs_examples/bin/modules/model_io/models/llms/integrations/ollama.dart, examples/docs_examples/bin/modules/retrieval/vector_stores/integrations/objectbox.dart, examples/hello_world_flutter/lib/home/bloc/providers.dart, examples/wikivoyage_eu/README.md, examples/wikivoyage_eu/bin/wikivoyage_eu.dart, examples/wikivoyage_eu/pubspec.yaml, packages/langchain_community/lib/src/vector_stores/objectbox/objectbox.dart, packages/langchain_ollama/lib/src/chat_models/chat_ollama/chat_ollama.dart, packages/langchain_ollama/lib/src/chat_models/chat_ollama_tools/chat_ollama_tools.dart, packages/langchain_ollama/lib/src/embeddings/ollama_embeddings.dart, packages/langchain_ollama/lib/src/llms/ollama.dart, packages/langchain_ollama/test/embeddings/ollama_test.dart, packages/langchain_ollama/test/llms/ollama_test.dart, packages/ollama_dart/example/ollama_dart_example.dart, packages/ollama_dart/oas/ollama-curated.yaml
https://ollama.com/library/llama3.1
=> feat!: Update Ollama default model to llama-3.1

docs/expression_language/cookbook/prompt_llm_parser.md, docs/expression_language/get_started.md, docs/expression_language/interface.md, docs/expression_language/primitives/binding.md, docs/expression_language/primitives/function.md, docs/expression_language/streaming.md, docs/modules/agents/agent_types/agent_types.md, docs/modules/model_io/models/chat_models/chat_models.md, examples/docs_examples/bin/expression_language/cookbook/prompt_llm_parser.dart, examples/docs_examples/bin/expression_language/cookbook/streaming.dart, examples/docs_examples/bin/expression_language/get_started.dart, examples/docs_examples/bin/expression_language/interface.dart, examples/docs_examples/bin/expression_language/primitives/binding.dart, examples/docs_examples/bin/expression_language/primitives/function.dart, packages/langchain_openai/lib/src/chains/qa_with_sources.dart, packages/langchain_openai/lib/src/chat_models/chat_openai.dart, packages/langchain_openai/test/chains/qa_with_sources_test.dart, packages/langchain_openai/test/chat_models/chat_openai_test.dart, packages/langchain_openai/test/chat_models/open_router_test.dart, packages/openai_dart/README.md, packages/openai_dart/lib/src/generated/schema/create_chat_completion_request.dart, packages/openai_dart/lib/src/generated/schema/create_run_request.dart, packages/openai_dart/lib/src/generated/schema/create_thread_and_run_request.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/test/openai_client_chat_test.dart
`gpt-3.5-turbo` -> `gpt-4o-mini`
=> feat!: Update ChatOpenAI default model to gpt-4o-mini

.gitignore, examples/browser_summarizer/pubspec.lock, examples/browser_summarizer/pubspec_overrides.yaml, examples/docs_examples/pubspec.lock, examples/docs_examples/pubspec_overrides.yaml, examples/hello_world_backend/pubspec.lock, examples/hello_world_backend/pubspec_overrides.yaml, examples/hello_world_cli/pubspec.lock, examples/hello_world_cli/pubspec_overrides.yaml, examples/hello_world_flutter/pubspec.lock, examples/hello_world_flutter/pubspec_overrides.yaml, examples/vertex_ai_matching_engine_setup/pubspec.lock, examples/wikivoyage_eu/pubspec.lock, examples/wikivoyage_eu/pubspec_overrides.yaml, packages/anthropic_sdk_dart/pubspec.lock, packages/langchain_chroma/pubspec_overrides.yaml, packages/langchain_firebase/example/pubspec.lock, packages/langchain_firebase/example/pubspec_overrides.yaml, packages/langchain_firebase/pubspec.lock, packages/langchain_google/pubspec_overrides.yaml, packages/langchain_mistralai/pubspec_overrides.yaml, packages/langchain_ollama/pubspec_overrides.yaml, packages/langchain_openai/pubspec_overrides.yaml, packages/langchain_pinecone/pubspec_overrides.yaml, packages/langchain_supabase/pubspec_overrides.yaml
Fixes https://github.com/dart-lang/build/issues/3733#issuecomment-2272082820
=> build: Upgrade pubspec.lock files

docs/_sidebar.md, packages/langchain/README.md
=> docs: Add Code Assist AI in README and documentation

packages/langchain_google/lib/src/embeddings/google_ai/google_ai_embeddings.dart, packages/langchain_google/test/embeddings/google_ai/google_ai_embeddings_test.dart
https://github.com/google-gemini/generative-ai-dart/pull/149
=> feat: Add support for reduced output dimensionality in GoogleGenerativeAIEmbeddings

docs/expression_language/primitives/router.md, docs/modules/agents/agent_types/tools_agent.md, docs/modules/model_io/models/chat_models/integrations/ollama.md, docs/modules/model_io/models/llms/integrations/ollama.md, docs/modules/retrieval/text_embedding/integrations/ollama.md, docs/modules/retrieval/vector_stores/integrations/objectbox.md, examples/docs_examples/bin/expression_language/cookbook/routing.dart, examples/docs_examples/bin/modules/agents/agent_types/tools_agent.dart, examples/docs_examples/bin/modules/model_io/models/chat_models/integrations/ollama.dart, examples/docs_examples/bin/modules/model_io/models/llms/integrations/ollama.dart, examples/docs_examples/bin/modules/retrieval/vector_stores/integrations/objectbox.dart, examples/hello_world_flutter/lib/home/bloc/providers.dart, examples/wikivoyage_eu/README.md, examples/wikivoyage_eu/bin/wikivoyage_eu.dart, examples/wikivoyage_eu/pubspec.yaml, packages/langchain_community/lib/src/vector_stores/objectbox/objectbox.dart, packages/langchain_ollama/lib/src/chat_models/chat_ollama/chat_ollama.dart, packages/langchain_ollama/lib/src/embeddings/ollama_embeddings.dart, packages/langchain_ollama/lib/src/llms/ollama.dart, packages/langchain_ollama/test/chat_models/chat_ollama_test.dart, packages/langchain_ollama/test/embeddings/ollama_test.dart, packages/langchain_ollama/test/llms/ollama_test.dart, packages/ollama_dart/README.md, packages/ollama_dart/example/ollama_dart_example.dart, packages/ollama_dart/oas/ollama-curated.yaml, packages/ollama_dart/test/ollama_dart_chat_test.dart
https://ai.meta.com/blog/llama-3-2-connect-2024-vision-edge-mobile-devices/
=> feat: Update Ollama default model to llama-3.2

packages/langchain/lib/src/embeddings/cache.dart
=> refactor: Update deprecated UUID constant

examples/browser_summarizer/pubspec.lock, examples/docs_examples/pubspec.lock, examples/hello_world_backend/pubspec.lock, examples/hello_world_cli/pubspec.lock, examples/hello_world_flutter/pubspec.lock, examples/wikivoyage_eu/pubspec.lock, melos.yaml, packages/langchain/lib/src/embeddings/cache.dart, packages/langchain/pubspec.yaml, packages/langchain/test/embeddings/cache.dart, packages/langchain_chroma/pubspec.yaml, packages/langchain_community/pubspec.yaml, packages/langchain_firebase/example/pubspec.lock, packages/langchain_firebase/pubspec.lock, packages/langchain_firebase/pubspec.yaml, packages/langchain_google/pubspec.yaml, packages/langchain_ollama/pubspec.yaml, packages/langchain_openai/pubspec.yaml, packages/langchain_pinecone/pubspec.yaml
=> fix: UUID 'Namespace' can't be assigned to the parameter type 'String?'

packages/anthropic_sdk_dart/lib/src/generated/schema/schema.freezed.dart, packages/anthropic_sdk_dart/oas/anthropic_openapi_curated.yaml
According to the OpenAPI specification, if the mapping is not provided, the property is assumed to contain the type name, which is clearly not the case in this case.
https://swagger.io/docs/specification/v3_0/data-models/inheritance-and-polymorphism/
=> Update anthropic_openapi_curated.yaml to add discriminator mapping

packages/openai_dart/README.md
Resolves https://github.com/davidmigloz/langchain_dart/issues/575
=> docs: Fix openai_dart assistants API outdated documentation

examples/browser_summarizer/pubspec.lock, examples/docs_examples/pubspec.lock, examples/wikivoyage_eu/pubspec.lock, melos.yaml, packages/langchain_community/pubspec.yaml
Ref: https://github.com/objectbox/objectbox-dart/issues/676
=> fix: Update ObjectBox SDK to v4.0.3 to fix StorageException in iOS

packages/openai_dart/README.md
https://techcrunch.com/2024/10/21/xai-elon-musks-ai-startup-launches-an-api/
=> docs: Add xAI to list of OpenAI-compatible APIs in openai_dart

packages/anthropic_sdk_dart/README.md, packages/anthropic_sdk_dart/lib/src/generated/schema/create_message_request.dart, packages/anthropic_sdk_dart/lib/src/generated/schema/schema.g.dart, packages/anthropic_sdk_dart/oas/anthropic_openapi_curated.yaml, packages/anthropic_sdk_dart/test/messages_test.dart
https://www.anthropic.com/news/3-5-models-and-computer-use
=> feat: Add claude-3-5-sonnet-20241022 to model catalog in anthropic_sdk_dart

packages/anthropic_sdk_dart/oas/anthropic_openapi_curated.yaml
=> fix: Added missing discriminator mapping to anthropic_openapi_curated.yaml

packages/openai_dart/README.md, packages/openai_dart/lib/src/generated/schema/chat_completion_audio_options.dart, packages/openai_dart/lib/src/generated/schema/chat_completion_audio_voice.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/oas/openapi_official.yaml
New voices:
- ash
- ballad
- coral
- sage
- verse
=> feat: Add five new voice types to Chat Completions API in openai_dart

packages/openai_dart/lib/src/generated/schema/create_chat_completion_request.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml
=> fix: Default store field to null in openai_dart to support Azure and Groq APIs

packages/langchain_community/lib/src/vector_stores/objectbox/objectbox.dart
=> feat: Expose internal store in ObjectBoxVectorStore

packages/langchain_openai/lib/src/chat_models/types.dart, packages/openai_dart/README.md, packages/openai_dart/lib/src/generated/schema/create_assistant_request.dart, packages/openai_dart/lib/src/generated/schema/create_chat_completion_request.dart, packages/openai_dart/lib/src/generated/schema/create_run_request.dart, packages/openai_dart/lib/src/generated/schema/create_thread_and_run_request.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/oas/openapi_official.yaml
https://platform.openai.com/docs/models#gpt-4o
> GPT-4o got an update 🎉
> The model’s creative writing ability has leveled up–more natural, engaging, and tailored writing to improve relevance & readability.
> It’s also better at working with uploaded files, providing deeper insights & more thorough responses.
https://x.com/OpenAI/status/1859296125947347164
=> feat: Add gpt-4o-2024-11-20 to model catalog in openai_dart

packages/openai_dart/README.md
Ref: https://learn.microsoft.com/en-us/azure/ai-services/openai/assistants-reference-threads?tabs=python
Relates to #606
=> docs: Document Azure Assistants API base url

packages/openai_dart/lib/src/generated/schema/create_run_request.dart, packages/openai_dart/lib/src/generated/schema/create_thread_and_run_request.dart, packages/openai_dart/lib/src/generated/schema/run_object.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/lib/src/generated/schema/truncation_object.dart, packages/openai_dart/oas/openapi_curated.yaml
=> chore: fix typo

packages/openai_realtime_dart/lib/src/schema/generated/schema/realtime_event.dart, packages/openai_realtime_dart/lib/src/schema/generated/schema/schema.freezed.dart, packages/openai_realtime_dart/lib/src/schema/generated/schema/schema.g.dart, packages/openai_realtime_dart/oas/openai_spec_curated.yaml
=> fix: previous_item_id should be nullable in openai_realtime_dart

packages/langchain_core/lib/src/runnables/map.dart, packages/langchain_core/test/runnables/map_test.dart
=> fix: RunnableMap doesn't invoke multiple Runnables in parallel

packages/openai_dart/lib/src/generated/schema/model.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/test/openai_client_compatible_apis.dart
=> feat: Make Model. created field nullable to support Google's OpenAI-compatible API

packages/openai_dart/lib/src/generated/schema/list_models_response.dart, packages/openai_dart/lib/src/generated/schema/model.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/test/openai_client_compatible_apis.dart
=> feat: Make Model.object/owned_by  fields nullable to support OpenRouter's OpenAI-compatible API

packages/langchain_core/test/tools/base_test.dart, packages/langchain_openai/lib/src/chat_models/mappers.dart, packages/openai_dart/lib/src/generated/schema/create_chat_completion_stream_response.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/test/openai_client_chat_test.dart, packages/openai_dart/test/openai_client_compatible_apis.dart
=> feat: Make CreateChatCompletionStreamResponse.choices field nullable to support Groq's OpenAI-compatible API

packages/langchain_firebase/lib/src/chat_models/vertex_ai/mappers.dart, packages/langchain_google/lib/src/chat_models/google_ai/mappers.dart, packages/langchain_google/test/chat_models/google_ai/chat_google_generative_ai_test.dart
Resolves #753
Gemini/Vertex can emit multiple `FunctionCall` parts in a single model turn. The next turn must be a single `functionResponses` content with the same number of `FunctionResponse` parts, in order. We previously sent each `ToolChatMessage` as its own turn, causing the SDK error:
```
Please ensure that the number of function response parts is equal to the number of function call parts of the function call turn.
```
This change accumulates consecutive `ToolChatMessages` and flushes them as one `functionResponses([...])`.
=> fix: Batch sequential tool responses in GoogleAI & Firebase VertexAI
