packages/langchain/lib/src/memory/buffer_window.dart, packages/langchain/lib/src/memory/memory.dart, packages/langchain/test/memory/buffer_window_test.dart
Add support for ConversationBufferWindowMemory. Uses a limited size window to retrieve messages at a later time.
Issue related #25
Dependencies: None
- General: @davidmigloz
=> feat(memory): add ConversationBufferWindowMemory

packages/langchain/lib/src/memory/stores/message/history.dart, packages/langchain/lib/src/memory/stores/message/in_memory.dart, packages/langchain/lib/src/memory/token_buffer.dart, packages/langchain/test/memory/stores/message/in_memory_test.dart, packages/langchain/test/memory/token_buffer_test.dart
Add support for ConversationBufferWindowMemory.  Uses token length to limit the buffer size.
Issue related #26
Dependencies: None
@davidmigloz
I have some doubts about the API of `removeOldestMessage`. It could be `removeAt` and handle it as Dart does. I prefer this way as it maintains the same syntax of other methods.
=> Feat: ConversationTokenBufferMemory

packages/langchain/lib/src/memory/summary.dart, packages/langchain/lib/src/memory/token_buffer.dart, packages/langchain/test/memory/summary_test.dart
Adds support for ConversationSummaryMemory.
Some considerations:
- Store prompt text and the default prompt as a static default inside the memory class
- As the python package, it only support prompts using `summary` and `new_lines`. We could change this in the future ;)
- I did not use a factory to generate with previous messages as the the summarization is done async.
Issue: #27 
Dependencies: None
Maintainer @davidmigloz
=> feat: add ConversationSummaryMemory

packages/langchain/lib/src/documents/vector_stores/base.dart
- Description: I noticed always 4 documents were returned from search. Seems like it wasn't get passed to similaritySearch, maxMarginalRelevanceSearch.
- Tag maintainer: @davidmigloz
- General: @davidmigloz
See contribution guidelines for more information on how to write/run tests, lint, etc: 
https://github.com/davidmigloz/langchain_dart/blob/main/CONTRIBUTING.md
=> fix(stores): variable k was not getting passed

packages/langchain/lib/src/documents/vector_stores/memory.dart, packages/langchain/test/documents/vector_stores/memory_test.dart
- The document id is now used as id in the `MemoryVectorStore` entries
- You can now delete entries with the `MemoryVectorStore.delete` method
- You can now specify a list of `initialMemoryVectors` to initialize the vector store with 
- Added `MemoryVector.fromMap` and `MemoryVector.toMap()` to de/serialize `MemoryVector`
=> feat(stores): Initial vectors, ids, and delete in MemoryVectorStore

packages/langchain_openai/lib/src/agents/functions.dart
**Description**: The prompt of the default LLMChain(`OpenAIFunctionsAgent.fromLLMAndTools`) has a wrong order when no memory and causing infinite loop of function call.
**Issue**: infinite loop of function call with OpenAIFunctionsAgent
**Tag maintainer**:  @davidmigloz
**Background**:
When using `OpenAIFunctionsAgent.fromLLMAndTools` and `memory == null`, `createPrompt` will create prompt with the following order:
```
System
AgentScratchPad
Human
```
Even when the agent finishes the task, GPT appears to trigger the function repeatedly because the last message is a Human message.
Example of `promptValue` that calling infinite loop:
**Solution**:
I change the default order of `createPrompt` when no memory to the following and the issue is gone.
```
System
Human
AgentScratchPad
```
=> fix(agent): openai function agent infinite loop issue

packages/langchain/lib/src/memory/vector_store.dart, packages/langchain/test/memory/vector_store_test.dart
VectorStoreRetrieverMemory is now called VectorStoreMemory and it takes a vector store instead of a VectorStoreRetriever.
Reason: I'm going to remove the `VectorStoreRetriever.addDocuments` method, as a retriever should only be able to fetch data, not write data as well.
=> refactor(memory)!: Rename VectorStoreRetrieverMemory

packages/langchain/lib/src/documents/retrievers/vector_store.dart, packages/langchain/lib/src/documents/vector_stores/base.dart
A retriever should only be able to fetch data, not write data as well.
=> refactor(retrievers)!: Remove addDocuments from VectorStoreRetriever

packages/vertex_ai/lib/src/gen_ai/models/text.dart, packages/vertex_ai/lib/src/gen_ai/models/text_chat.dart, packages/vertex_ai/test/gen_ai/mappers/chat_test.dart, packages/vertex_ai/test/gen_ai/mappers/text_test.dart
Ref:
- https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text
- https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text-chat
(Although the don't seem to be taken into account by the current models yet)
=> feat(vertex_ai): Add support for stopSequence and candidateCount

packages/langchain_google/lib/src/chat_models/vertex_ai.dart, packages/langchain_google/lib/src/embeddings/vertex_ai.dart, packages/langchain_google/lib/src/llms/vertex_ai.dart
VertexAI embeddings models released in August support a new "task type" parameter that indicates the kind of task the embeddings is going to be used for, this helps the model produce better quality embeddings.
If you are using a model that supports it, LangChain.dart will use 'RETRIEVAL_DOCUMENT' when embedding a document and 'RETRIEVAL_QUERY' when embedding a query.
Docs:
https://cloud.google.com/vertex-ai/docs/generative-ai/embeddings/get-text-embeddings#api_changes_to_models_released_in_or_after_august_2023
=> feat(embeddings): Support task type in VertexAI embeddings models

packages/langchain/lib/src/documents/embeddings/base.dart, packages/langchain/lib/src/documents/embeddings/cache.dart, packages/langchain/lib/src/documents/embeddings/fake.dart, packages/langchain/lib/src/documents/vector_stores/base.dart, packages/langchain/test/chains/retrieval_qa_test.dart, packages/langchain/test/documents/embeddings/cache.dart, packages/langchain/test/documents/embeddings/fake.dart, packages/langchain/test/documents/vector_stores/memory_test.dart, packages/langchain/test/memory/vector_store_test.dart, packages/langchain_google/lib/src/embeddings/vertex_ai.dart, packages/langchain_google/test/embeddings/vertex_ai_test.dart, packages/langchain_google/test/vector_stores/matching_engine_test.dart, packages/langchain_openai/lib/src/embeddings/openai.dart, packages/langchain_openai/test/embeddings/openai_test.dart
Currently `Embeddings.embedDocuments` method takes a `List<String>` which is not ideal because:
1. It is not consistent with the name of the method
2. Some embedding models allow to pass some metadata to improve the quality of the generated embedding (e.g. VertexAI allows to pass a 'title' property)
This PR refactors the method to expect a `List<Document>` instead. Making it more aligned with the method name and allowing to pass metadata to the embedding models.
=> refactor(embeddings)!: Change embedDocuments input to List<Document>

packages/langchain_google/lib/src/chat_models/vertex_ai.dart, packages/langchain_google/lib/src/embeddings/vertex_ai.dart, packages/langchain_google/lib/src/llms/vertex_ai.dart, packages/langchain_google/test/embeddings/vertex_ai_test.dart, packages/langchain_google/test/vector_stores/matching_engine_test.dart
Embedding models released after August 2023 support specifying a document title when embedding documents. The title is then used by the model to improve the quality of the embeddings.
=> feat(embeddings): Support document title in VertexAIEmbeddings

packages/langchain_google/example/langchain_google_example.dart, packages/langchain_google/lib/src/chat_models/models/models.dart, packages/langchain_google/lib/src/chat_models/vertex_ai.dart, packages/langchain_google/lib/src/llms/models/models.dart, packages/langchain_google/lib/src/llms/vertex_ai.dart, packages/langchain_google/test/chat_models/vertex_ai_test.dart, packages/langchain_google/test/llms/vertex_ai_test.dart
Before if you wanted to change any model options (e.g. temperature) you needed to create a new instance of the model wrapper. Now, we have a `defaultOptions` parameter that allows to configure the default options but you can always override them when calling the model with the `options` parameter.
Example:
```dart
final chatModel = ChatVertexAI(
authHttpClient: authClient,
project: 'your-project-id',
defaultOptions: ChatVertexAIOptions(
temperature: 0.9,
),
);
final result = await chatModel(
[ChatMessage.human('Hello')],
options: ChatVertexAIOptions(
temperature: 0.5,
),
);
```
This PR also adds support for two new options:
- `stopSequences`: Specifies a list of strings that tells the model to stop generating text if one of the strings is encountered in the response. If a string appears …
=> feat(llms)!: Add default and call options in VertexAI and ChatVertexAI

examples/vertex_ai_matching_engine_setup/bin/vertex_ai_matching_engine_setup.dart, packages/langchain_google/example/langchain_google_example.dart, packages/langchain_google/lib/src/chat_models/vertex_ai.dart, packages/langchain_google/lib/src/embeddings/vertex_ai.dart, packages/langchain_google/lib/src/llms/vertex_ai.dart, packages/langchain_google/lib/src/vector_stores/matching_engine.dart, packages/langchain_google/test/chat_models/vertex_ai_test.dart, packages/langchain_google/test/embeddings/vertex_ai_test.dart, packages/langchain_google/test/llms/vertex_ai_test.dart, packages/langchain_google/test/vector_stores/matching_engine_test.dart, packages/langchain_pinecone/pubspec.yaml, packages/langchain_pinecone/pubspec_overrides.yaml, packages/langchain_pinecone/test/vector_stores/pinecone_test.dart, packages/vertex_ai/example/vertex_ai_example.dart, packages/vertex_ai/lib/src/gen_ai/gen_ai_client.dart, packages/vertex_ai/lib/src/matching_engine/matching_engine_client.dart, packages/vertex_ai/test/gen_ai/gen_ai_client_test.dart, packages/vertex_ai/test/matching_engine/maching_engine_client_test.dart
Currently all VertexAI wrapper require a `AuthHttp` instance from `googleapis_auth` package. However, you may want to use a proxy server instead of calling directly VertexAI. Requiring an `http.Client` instead of  `AuthClient` gives you the flexibility to do that. As you can create your own wrapper of `http.Client` to handle the authentication of your proxy.
=> refactor(vertex_ai): Require `http.Client` instead of `AuthClient`

packages/langchain_pinecone/pubspec.yaml
@davidmigloz This should resolve the regression you note in the `pubspec.yaml` file for `v0.5.2`.
The relevant changes to the the [pinecone](https://pub.dev/packages/pinecone) package are linked below. An accidental regression leaked where the security scheme for the client generation was not getting populated. In turn, it was defaulting to `http` instead of `https`. 
Performed a manual end-to-end test on Pinecone production servers to ensure this is now working as expected. Applying the patch update here to `langchain_pinecone`.
https://github.com/tazatechnology/pinecone/commit/dcbcdf5a427626f9037b9117b82246a9742e3b14
=> Update pinecone dependency - regression resolved

packages/langchain_pinecone/lib/src/vector_stores/pinecone.dart, packages/langchain_pinecone/pubspec.yaml
pinecone v0.6.0 had a breaking change that was breaking langchain_pinecone implementation (`host` renamed to `baseUrl`)
=> feat(vector-stores): Upgrade pinecone client to v0.6.0

packages/langchain_openai/lib/src/chat_models/openai.dart, packages/langchain_openai/lib/src/llms/openai.dart
With the migration to `openai_dart` client I left `OpenAI.maxTokens` default to `null`, which then uses the default value from OpenAI (16 tokens) which is very low compared to the previous default value (256). 
This PR reverts the default to 256 tokens.
=> fix(llms): Revert OpenAI maxTokens default to 256

docs/expression_language/cookbook/prompt_llm_parser.md, examples/docs_examples/bin/expression_language/cookbook/prompt_llm_parser.dart, packages/langchain/lib/src/core/runnable/base.dart, packages/langchain/lib/src/core/runnable/binding.dart, packages/langchain/lib/src/core/runnable/map.dart, packages/langchain/lib/src/core/runnable/sequence.dart, packages/langchain/lib/src/model_io/chat_models/models/models.dart, packages/langchain/lib/src/model_io/output_parsers/functions.dart, packages/langchain/lib/src/model_io/output_parsers/output_parser.dart, packages/langchain/lib/src/model_io/output_parsers/utils/json.dart, packages/langchain/test/core/runnable/stream_test.dart, packages/langchain/test/model_io/output_parsers/functions_test.dart, packages/langchain/test/model_io/output_parsers/utils/json_test.dart
Example:
```dart
const function = ChatFunction(
name: 'joke',
description: 'A joke',
parameters: {
'type': 'object',
'properties': {
'setup': {
'type': 'string',
'description': 'The setup for the joke',
},
'punchline': {
'type': 'string',
'description': 'The punchline to the joke',
},
},
'required': ['location', 'punchline'],
},
);
final promptTemplate = ChatPromptTemplate.fromTemplate(
'tell me a long joke about {foo}',
);
final chat = ChatOpenAI(apiKey: openaiApiKey, temperature: 0).bind(
ChatOpenAIOptions(
functions: const [function],
functionCall: ChatFunctionCall.forced(functionName: 'joke'),
),
);
final jsonOutputParser = JsonOutputFunctionsParser();
final chain = promptTemplate.pipe(chat).pipe(jsonOutputParser);
final stream = chain.stream({'foo': 'bears'});
await for (final res in …
```
=> feat(output-parsers): Add streaming support to OutputFunctionsParsers

packages/langchain_openai/lib/src/llms/models/mappers.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/langchain_openai/test/llms/openai_test.dart
Relates to #4 
Example:
```dart
final promptTemplate = PromptTemplate.fromTemplate(
'List the numbers from 1 to {max_num} in order without any spaces or commas',
);
final llm = OpenAI(apiKey: openaiApiKey);
const stringOutputParser = StringOutputParser<String>();
final chain = promptTemplate.pipe(llm).pipe(stringOutputParser);
final stream = chain.stream({'max_num': '9'});
String content = '';
await for (final res in stream) {
content += res;
print(content);
}
```
will print:
```
123
12345
1234567
123456789
```
=> feat(llms): Add streaming support to OpenAI

packages/langchain_openai/lib/src/chains/qa_with_sources.dart, packages/langchain_openai/lib/src/chat_models/models/mappers.dart, packages/langchain_openai/lib/src/chat_models/openai.dart, packages/langchain_openai/test/chat_models/openai_test.dart
Relates to #4 
Example:
```dart
final promptTemplate = ChatPromptTemplate.fromPromptMessages([
SystemChatMessagePromptTemplate.fromTemplate(
'You are a helpful assistant that replies only with numbers '
'in order without any spaces or commas',
),
HumanChatMessagePromptTemplate.fromTemplate(
'List the numbers from 1 to {max_num}',
),
]);
final chat = ChatOpenAI(apiKey: openaiApiKey);
const stringOutputParser = StringOutputParser<ChatMessage>();
final chain = promptTemplate.pipe(chat).pipe(stringOutputParser);
final stream = chain.stream({'max_num': '9'});
String content = '';
await for (final res in stream) {
content += res;
print(content);
}
```
will print:
```
123
123456
123456789
```
=> feat(chat-models): Add streaming support to ChatOpenAI

packages/openai_dart/lib/src/generated/schema/create_image_request.dart, packages/openai_dart/lib/src/generated/schema/image.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/test/openai_client_images_test.dart
- `dall-e-2` and `dall-e-3` models support
- `standard` and `hd` quality support
- `1792x1024` and `1024x1792` image size support
- `vivid` and `natural` style support
- `revised_prompt` support
> Developers can integrate DALL·E 3, which we recently launched to ChatGPT Plus and Enterprise users, directly into their apps and products through our Images API by specifying dall-e-3 as the model. Companies like Snap, Coca-Cola, and Shutterstock have used DALL·E 3 to programmatically generate images and designs for their customers and campaigns. Similar to the previous version of DALL·E, the API incorporates built-in moderation to help developers protect their applications against misuse. We offer different format and quality options, with prices starting at $0.04 per image generated. Check out …
=> feat(openai_dart): Support new images API functionality

packages/langchain_openai/lib/src/llms/models/mappers.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/langchain_openai/test/llms/openai_test.dart
Example:
```dart
test('Test response seed', () async {
final prompt = PromptValue.string('How are you?');
final llm = OpenAI(
temperature: 0,
seed: 9999,
);
final res1 = await llm.invoke(prompt);
expect(res1.generations, hasLength(1));
final generation1 = res1.generations.first;
final res2 = await llm.invoke(prompt);
expect(res2.generations, hasLength(1));
final generation2 = res2.generations.first;
expect(
res1.modelOutput?['systemFingerprint'],
res2.modelOutput?['systemFingerprint'],
);
expect(generation1.output, generation2.output);
});
```
=> feat(llms): Support seed and system_fingerprint in OpenAI wrapper

packages/openai_dart/lib/src/client.dart, packages/openai_dart/lib/src/http_client/http_client_html.dart, packages/openai_dart/lib/src/http_client/http_client_io.dart, packages/openai_dart/lib/src/http_client/http_client_stub.dart
The `fetch_client` that `openai_dart` uses when targeting web maps `keepalive` to [`BaseRequest.persistentConnection`](https://pub.dev/documentation/http/latest/http/BaseRequest/persistentConnection.html)
which is **`true`** by default.
Fetch spec says that maximum request size with `keepalive` flag is 64KiB:
> __4.5. HTTP-network-or-cache fetch__
>
> > 8.10.5: If the sum of _contentLength_ and _inflightKeepaliveBytes_ is greater
> > than 64 kibibytes, then return a [network error](https://fetch.spec.whatwg.org/#concept-network-error).
> 
> _Source: [Fetch. Living Standard — Last Updated 19 June 2023](https://fetch.spec.whatwg.org/#http-network-or-cache-fetch)_
Therefore if the request is larger than 64KiB (this includes some other data, so effectively recommended check is _60KiB_) we …
=> fix(openai_dart): Fetch requests with big payloads dropping connection

docs/expression_language/cookbook/multiple_chains.md, docs/expression_language/cookbook/prompt_llm_parser.md, docs/expression_language/cookbook/tools.md, docs/expression_language/interface.md, examples/docs_examples/bin/expression_language/cookbook/multiple_chains.dart, examples/docs_examples/bin/expression_language/cookbook/prompt_llm_parser.dart, examples/docs_examples/bin/expression_language/cookbook/tools.dart, examples/docs_examples/bin/expression_language/interface.dart, packages/langchain/lib/src/core/runnable/base.dart, packages/langchain/lib/src/core/runnable/input_getter.dart, packages/langchain/test/core/runnable/input_getter_test.dart, packages/langchain/test/core/runnable/passthrough_test.dart
`RunnableMapFromItem` has been renamed to `RunnableMapFromInput`.
And its corresponding factory from `Runnable.getMapFromItem()` to `Runnable.getMapFromInput()`.
=> refactor(lcel): Rename RunnableMapFromItem to RunnableMapFromInput

docs/expression_language/interface.md, examples/docs_examples/bin/expression_language/interface.dart, packages/langchain/lib/src/core/runnable/base.dart, packages/langchain/lib/src/core/runnable/input_map.dart, packages/langchain/lib/src/core/runnable/runnable.dart, packages/langchain/test/core/runnable/input_map_test.dart
A `RunnableMapInput` allows you to map the input to a different value.
You can create a `RunnableMapInput` using the `Runnable.mapInput` static method.
When you call `invoke` on a `RunnableMapInput`, it will take the input it receives and returns the output returned by the given `inputMapper` function.
Example:
```dart
final agent = Agent.fromRunnable(
Runnable.mapInput(
(final AgentPlanInput planInput) => <String, dynamic>{
'input': planInput.inputs['input'],
'agent_scratchpad': buildScratchpad(planInput.intermediateSteps),
},
).pipe(prompt).pipe(model).pipe(outputParser),
tools: [tool],
);
```
=> feat(lcel): Add support for Runnable.mapInput()

packages/langchain/lib/src/storage/file_system_io.dart, packages/langchain/lib/src/storage/file_system_stub.dart, packages/langchain/lib/src/storage/storage.dart
Currently, pub.dev doesn't show web as a supported platform because `LocalFileStore` depends on `dart:io`.
This PR implements a stub of `LocalFileStore` for web and conditionally exports it.
=> fix(storage): Conditionally import dart:io in LocalFileStore

packages/langchain_google/lib/src/llms/models/models.dart, packages/langchain_google/lib/src/llms/vertex_ai.dart, packages/langchain_google/test/llms/vertex_ai_test.dart
The fields `publisher` and `model` have been moved from `VertexAI` to `VertexAIOptions`.
Before:
```dart
final llm = VertexAI(
httpClient: authHttpClient,
project: Platform.environment['VERTEX_AI_PROJECT_ID']!,
publisher: 'google',
model: 'text-bison@001',
defaultOptions: const VertexAIOptions(
temperature: 0.1,
),
);
```
Now:
```dart
final llm = VertexAI(
httpClient: authHttpClient,
project: Platform.environment['VERTEX_AI_PROJECT_ID']!,
defaultOptions: const VertexAIOptions(
publisher: 'google',
model: 'text-bison@001',
temperature: 0.1,
),
);
```
=> feat(llms)!: Move all model config options to VertexAIOptions

packages/langchain_google/lib/src/chat_models/models/models.dart, packages/langchain_google/lib/src/chat_models/vertex_ai.dart, packages/langchain_google/test/chat_models/vertex_ai_test.dart
The fields `publisher` and `model` have been moved from `ChatVertexAI` to `ChatVertexAIOptions`.
Before:
```dart
final llm = ChatVertexAI(
httpClient: authHttpClient,
project: Platform.environment['VERTEX_AI_PROJECT_ID']!,
publisher: 'google',
model: 'chat-bison@001',
defaultOptions: const ChatVertexAIOptions(
temperature: 0.1,
),
);
```
Now:
```dart
final llm = ChatVertexAI(
httpClient: authHttpClient,
project: Platform.environment['VERTEX_AI_PROJECT_ID']!,
defaultOptions: const ChatVertexAIOptions(
publisher: 'google',
model: 'chat-bison@001',
temperature: 0.1,
),
);
```
=> feat(chat-models)!: Move all model config options to ChatVertexAIOptions

docs/modules/agents/agent_types/openai_functions_agent.md, docs/modules/agents/tools/openai_dall_e.md, examples/docs_examples/bin/modules/agents/agent_types/openai_functions_agent.dart, examples/docs_examples/bin/modules/agents/tools/openai_dalle.dart, packages/langchain/lib/src/agents/tools/base.dart, packages/langchain/lib/src/agents/tools/calculator.dart, packages/langchain/lib/src/agents/tools/exception.dart, packages/langchain/lib/src/agents/tools/invalid.dart, packages/langchain/lib/src/agents/tools/models/models.dart, packages/langchain/lib/src/agents/tools/tools.dart, packages/langchain/test/agents/executors_test.dart, packages/langchain/test/agents/tools/base_test.dart, packages/langchain_openai/lib/src/agents/functions.dart, packages/langchain_openai/test/agents/functions_test.dart
Before it was only possible to pass parameters to your tools when creating the tool instance. Now you can pass tool options when calling the tools in the same way you can pass options to your llms.
Eg.
```dart
final dallETool = OpenAIDallETool(apiKey: openAiKey);
final res1 = await dallETool.invoke(
{'input': 'Prompt'},
options: const OpenAIDallEToolOptions(
quality: ImageQuality.hd,
style: ImageStyle.vivid,
),
);
final res2 = await dallETool.invoke(
{'input': 'Prompt'},
options: const OpenAIDallEToolOptions(
quality: ImageQuality.standard,
style: ImageStyle.natural,
),
);
```
You can also use `bind` on your runnable pipelines to bind some options to the tool:
```dart
dallETool.bind(
const OpenAIDallEToolOptions(
model: 'dall-e-2',
),
);
``` 
You will have to add the new options parameter …
=> feat(tools)!: Allow to pass call options to tools

packages/langchain_openai/lib/src/agents/tools/dall_e.dart, packages/langchain_openai/lib/src/agents/tools/models/models.dart, packages/langchain_openai/lib/src/agents/tools/tools.dart, packages/langchain_openai/test/agents/tools/dall_e_test.dart
Similar to https://github.com/davidmigloz/langchain_dart/pull/232
All DallE config options have been moved from the constructor to `OpenAIDallEToolOptions`.
Before:
```dart
final tool = OpenAIDallETool(
apiKey: openAiKey,
model: 'dall-e-2',
size: ImageSize.v256x256,
);
```
After:
```dart
final tool = OpenAIDallETool(
apiKey: openAiKey,
defaultOptions: const OpenAIDallEToolOptions(
model: 'dall-e-2',
size: ImageSize.v256x256,
),
);
```
---
Before it was only possible to pass parameters to your tools when creating the tool instance. Now you can pass tool options when calling the tools in the same way you can pass options to your llms.
Eg.
```dart
final dallETool = OpenAIDallETool(apiKey: openAiKey);
final res1 = await dallETool.invoke(
{'input': 'Prompt'},
options: const …
```
=> feat(tools)!: Move all DallE config options to OpenAIDallEToolOptions

packages/langchain/lib/src/documents/loaders/json.dart
JsonPath has a dedicated method to read values only. This is a tiny cleanup/readability change.
=> Use JsonPath.readValues() 

packages/langchain_openai/lib/src/agents/tools/dall_e.dart, packages/langchain_openai/lib/src/chat_models/openai.dart, packages/langchain_openai/lib/src/embeddings/openai.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/openai_dart/lib/src/client.dart
You can now update the OpenAI key at any moment:
```dart
final llm = OpenAI(); // You can instantiate without a key
final key = getKeyFromUser();  // Ask user for the key
llm.apiKey = key; // Update key
lllm.invoke(...); // Use the wrapper
```
Supported in:
- `OpenAI`
- `ChatOpenAI`
- `OpenAIEmbeddings`
- `OpenAIDallETool`
=> feat: Allow to update OpenAI key without having to recreate the wrapper

packages/langchain/lib/src/core/runnable/map.dart, packages/langchain/lib/src/model_io/prompts/base_prompt.dart, packages/langchain_openai/test/chains/qa_with_sources_test.dart
When calling stream in a pipeline that contains a `PromptTemplate`,  `PromptTemplate` should wait to receive all the input values it needs before formatting the prompt and emitting it. Otherwise, it throws an exception when trying to format the prompt as not all the input values may have been emitted.
=> fix(prompts): PromptTemplate stream should only emit if it has all inputs

docs/expression_language/cookbook/retrieval.md, examples/docs_examples/bin/expression_language/cookbook/retrieval.dart, packages/langchain/lib/src/chains/retrieval_qa.dart, packages/langchain/lib/src/documents/retrievers/base.dart, packages/langchain/lib/src/documents/retrievers/fake.dart, packages/langchain/lib/src/documents/retrievers/models/models.dart, packages/langchain/lib/src/documents/retrievers/retrievers.dart, packages/langchain/lib/src/documents/retrievers/vector_store.dart, packages/langchain/lib/src/documents/vector_stores/base.dart
Continuing the efforts to add full LCEL support to all core components.
In this case, the `Retriever` class didn't allow to pass any options when invoking it. `VectorStoreRetriever` only supported config options in the constructor, which forced users to re-create the retriever every time they wanted to change the options.
A typical use case that was hard to implement was to do an initial search with a high `scoreThreshold` and then repeat the search with a lower `scoreThreshold` if the first search didn't return any results.
Now the `Retriever` classes support defining default options when instantiating them, but you can always override them when invoking the retriever.
```dart
const query = 'How much does my order cost?';
// Default options
final retriever = vectorStore.asRetriever( …
```
=> feat(retrievers)!: Move all retriever config options to RetrieverOptions

packages/langchain/lib/src/agents/tools/base.dart, packages/langchain/lib/src/agents/tools/calculator.dart
Eg.
```dart
final class CalculatorTool extends Tool<ToolOptions> {
CalculatorTool()
: super(
name: 'calculator',
description: 'Useful for getting the result of a math expression that could be executed by a simple calculator.',
inputDescription: 'A valid mathematical expression to evaluate',
);
// ...
}
```
Or from a function:
```dart
final myTool = Tool.fromFunction(
name: 'myTool',
description: 'My tool description...',
inputDescription: 'Description of the input of my tool',
func: (
final String toolInput, {
final ToolOptions? options,
}) => //...,
);
```
=> feat(tools): Support customizing Tool input description

packages/langchain/lib/src/model_io/language_models/models/models.dart, packages/langchain/lib/src/model_io/prompts/base_chat_message_prompt.dart, packages/langchain/lib/src/model_io/prompts/base_chat_prompt.dart, packages/langchain/lib/src/model_io/prompts/base_prompt.dart, packages/langchain/lib/src/model_io/prompts/chat_prompt.dart, packages/langchain/lib/src/model_io/prompts/pipeline.dart, packages/langchain/lib/src/model_io/prompts/prompt.dart, packages/langchain/lib/src/model_io/prompts/prompt_selector.dart, packages/langchain/lib/src/model_io/prompts/prompts.dart, packages/langchain/lib/src/model_io/prompts/template.dart, packages/langchain/test/model_io/prompts/chat_prompt_test.dart, packages/langchain/test/model_io/prompts/prompt_test.dart, packages/langchain_openai/lib/src/agents/functions.dart
Added `ChatPromptTemplate.fromTemplates` convenient factory constructor:
```dart
final promptTemplate = ChatPromptTemplate.fromTemplates([
(ChatMessageType.system, 'You are a helpful assistant that translates {input_language} to {output_language}.'),
(ChatMessageType.human, '{text}'),
]);
final prompt = promptTemplate.formatPrompt({
'input_language': 'English',
'output_language': 'French',
'text': 'I love programming.',
});
final res = await chatModel.invoke(prompt);
```
If you need to use message placeholders:
```dart
final promptTemplate = ChatPromptTemplate.fromTemplates([
(ChatMessageType.system, 'You are a helpful AI assistant'),
(ChatMessageType.messagesPlaceholder, 'history'),
(ChatMessageType.messagePlaceholder, 'input'),
]);
```
In general, prefer using …
=> feat(prompts): Make ChatPromptTemplates more convenient to use

.github/workflows/test.yaml, packages/chromadb/pubspec.yaml, packages/googleai_dart/pubspec.yaml, packages/mistralai_dart/pubspec.yaml, packages/ollama_dart/pubspec.yaml, packages/openai_dart/pubspec.yaml
The CICD workflow throws the following error from time to time:
```
melos bootstrap
└> /home/runner/work/langchain_dart/langchain_dart
Running "flutter pub get" in workspace packages...
- googleai_dart
└> packages/googleai_dart
└> Failed to install.
Git error. Command: `git clone --mirror https://github.com/davidmigloz/openapi_spec /opt/hostedtoolcache/flutter/stable-3.16.5-x64/.pub-cache/git/cache/openapi_spec-cd3779bcae98e6d4eef6fcdf66ff9bf6228fe093`
Resolving dependencies...
stdout: 
stderr: Cloning into bare repository '/opt/hostedtoolcache/flutter/stable-3.16.5-x64/.pub-cache/git/cache/openapi_spec-cd3779bcae98e6d4eef6fcdf66ff9bf6228fe093'...
BUG: refs/files-backend.c:3055: initial ref transaction called with existing refs
exit code: -6
BootstrapException: Failed to install.: …
```
=> build: Attempt to fix git clone errors in CICD

CHANGELOG.md, examples/browser_summarizer/pubspec.lock, examples/docs_examples/pubspec.lock, examples/hello_world_backend/pubspec.lock, examples/hello_world_cli/pubspec.lock, examples/hello_world_flutter/pubspec.lock, packages/langchain/pubspec.yaml, packages/langchain_google/lib/src/chat_models/vertex_ai/chat_vertex_ai.dart, packages/langchain_google/lib/src/llms/vertex_ai.dart, packages/langchain_google/pubspec.yaml, packages/langchain_google/test/chat_models/chat_vertex_ai_test.dart, packages/langchain_google/test/llms/vertex_ai_test.dart, packages/langchain_mistralai/lib/src/chat_models/chat_mistralai.dart, packages/langchain_mistralai/pubspec.yaml, packages/langchain_mistralai/test/chat_models/chat_mistralai_test.dart, packages/langchain_ollama/lib/src/chat_models/chat_ollama.dart, packages/langchain_ollama/lib/src/llms/ollama.dart, packages/langchain_ollama/pubspec.yaml, packages/langchain_ollama/test/chat_models/chat_ollama_test.dart, packages/langchain_ollama/test/llms/ollama_test.dart, packages/langchain_openai/lib/src/chat_models/openai.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/langchain_openai/pubspec.yaml, packages/langchain_openai/test/chat_models/openai_test.dart, packages/langchain_openai/test/llms/openai_test.dart
Switched from the tiktoken package to langchain_tiktoken in order to resolve the extremely long build-time release-mode issue.
Original issue:
https://github.com/mvitlov/tiktoken/issues/5
The package owner didn't merge the pull request:
https://github.com/mvitlov/tiktoken/pull/6
So we're using the forked and refactored langchain_tiktoken package instead:
https://pub.dev/packages/langchain_tiktoken
=> Migrate tokenizer to langchain_tiktoken package

docs/_sidebar.md, docs/modules/model_io/models/chat_models/integrations/open_router.md, docs/modules/model_io/models/chat_models/integrations/together_ai.md, examples/browser_summarizer/pubspec.lock, examples/docs_examples/bin/modules/model_io/models/chat_models/integrations/together_ai.dart, examples/docs_examples/pubspec.lock, examples/hello_world_backend/pubspec.lock, examples/hello_world_cli/pubspec.lock, examples/hello_world_flutter/pubspec.lock, examples/vertex_ai_matching_engine_setup/pubspec.lock, packages/langchain_openai/lib/src/chat_models/chat_openai.dart, packages/langchain_openai/test/chat_models/together_ai_test.dart
https://docs.together.ai/docs/openai-api-compatibility
=> feat(chat-models): Support Together AI API in ChatOpenAI wrapper

packages/langchain_mistralai/lib/src/chat_models/chat_mistralai.dart, packages/langchain_mistralai/lib/src/chat_models/models/models.dart, packages/langchain_mistralai/test/chat_models/chat_mistralai_test.dart, packages/mistralai_dart/lib/src/generated/schema/chat_completion_request.dart, packages/mistralai_dart/lib/src/generated/schema/schema.freezed.dart, packages/mistralai_dart/lib/src/generated/schema/schema.g.dart, packages/mistralai_dart/oas/mistral_openapi_curated.yaml, packages/mistralai_dart/oas/mistral_openapi_official.yaml, packages/mistralai_dart/test/mistralai_dart_chat_completions_test.dart
The request body schema for Chat Completion changed. 
- We use now safe_prompt instead of safe_mode property.
- The max temperature is now 1 instead of 2.
@davidmigloz 
I have a big doubt about the "refactor" I chose for the PR. Because it's not a bug. More of a small breaking change.
=> refactor(mistral): update safe_mode property and max temperature in ChatCompletionRequest

packages/openai_dart/lib/src/generated/schema/create_embedding_response.dart, packages/openai_dart/lib/src/generated/schema/embedding.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/pubspec.yaml, packages/openai_dart/test/openai_client_embeddings_test.dart
https://www.together.ai/blog/embeddings-endpoint-release
=> feat: Support Together AI Embeddings API in openai_dart client

packages/langchain_openai/lib/src/agents/functions.dart, packages/langchain_openai/lib/src/chains/qa_with_structure.dart
Bug report: https://discord.com/channels/1123158322812555295/1192852680075378718/1192852680075378718
Affected classes:
- `OpenAIFunctionsAgent`
- `OpenAIQAWithStructureChain`
=> fix: Specified model is always overwritten in OpenAIFunctionsAgent

packages/langchain/lib/src/documents/embeddings/cache.dart, packages/langchain_openai/lib/src/chat_models/chat_openai.dart, packages/langchain_openai/lib/src/embeddings/openai.dart, packages/langchain_openai/lib/src/llms/openai.dart
The new default model of `OpenAIEmbeddings` wrapper is now `text-embedding-3-small`.
If you are not planning to migrate to `text-embedding-3-small`, you have to explicitly set the model to `text-embedding-ada-002`, otherwise `text-embedding-3-small` will be used.
```dart
final embeddings = OpenAIEmbeddings(
model: 'text-embedding-ada-002',
);
```
---
https://openai.com/blog/new-embedding-models-and-api-updates#new-embedding-models-with-lower-pricing
> text-embedding-3-small is our new highly efficient embedding model and provides a significant upgrade over its predecessor, the text-embedding-ada-002 model released in [December 2022](https://openai.com/blog/new-and-improved-embedding-model). 
>
> Stronger performance. Comparing text-embedding-ada-002 to …
=> feat!: Update OpenAIEmbeddings' default model to text-embedding-3-small

docs/_sidebar.md, docs/modules/retrieval/vector_stores/integrations/supabase.md, packages/langchain_supabase/README.md, packages/langchain_supabase/lib/langchain_supabase.dart, packages/langchain_supabase/lib/src/vector_stores/models/models.dart, packages/langchain_supabase/lib/src/vector_stores/supabase.dart, packages/langchain_supabase/lib/src/vector_stores/vector_stores.dart, packages/langchain_supabase/pubspec.yaml, packages/langchain_supabase/pubspec_overrides.yaml, packages/langchain_supabase/test/vector_stores/assets/example.txt, packages/langchain_supabase/test/vector_stores/supabase_test.dart
Resolves #69
This PR implements `langchain_supabase` mimicking the behavior from Python/JS LangChain and inspired by [Storing OpenAI embeddings in Postgres with pgvector](https://supabase.com/blog/openai-embeddings-postgres-vector)).
It also includes the unit tests inspired by `langchain_chroma`.
=> #69 add support for supabase vectorstore

packages/langchain_ollama/lib/src/chat_models/chat_ollama.dart, packages/langchain_ollama/lib/src/chat_models/models/models.dart, packages/langchain_ollama/lib/src/llms/models/models.dart, packages/langchain_ollama/lib/src/llms/ollama.dart, packages/ollama_dart/lib/src/generated/schema/generate_chat_completion_request.dart, packages/ollama_dart/lib/src/generated/schema/generate_completion_request.dart, packages/ollama_dart/lib/src/generated/schema/schema.freezed.dart, packages/ollama_dart/lib/src/generated/schema/schema.g.dart, packages/ollama_dart/oas/ollama-curated.yaml, packages/ollama_dart/pubspec.yaml, packages/ollama_dart/test/ollama_dart_chat_test.dart, packages/ollama_dart/test/ollama_dart_completions_test.dart, packages/ollama_dart/test/ollama_dart_embeddings_test.dart, packages/ollama_dart/test/ollama_dart_models_test.dart
https://github.com/ollama/ollama/releases/tag/v0.1.23
> `keepAlive`: How long (in minutes) to keep the model loaded in memory.
> - If set to a positive duration (e.g. 20), the model will stay loaded for the provided duration.
> - If set to a negative duration (e.g. -1), the model will stay loaded indefinitely.
> - If set to 0, the model will be unloaded immediately once finished.
> - If not set, the model will stay loaded for 5 minutes by default
=> feat: Add Ollama keep_alive param to control how long models stay loaded

docs/modules/model_io/model_io.md, docs/modules/model_io/models/chat_models/chat_models.md, docs/modules/model_io/models/chat_models/how_to/llm_chain.md, docs/modules/model_io/models/chat_models/how_to/streaming.md, docs/modules/model_io/models/llms/how_to/llm_streaming.md, docs/modules/model_io/models/llms/how_to/token_usage_tracking.md, docs/modules/model_io/models/llms/llms.md, examples/docs_examples/bin/expression_language/get_started.dart, packages/langchain/lib/src/chains/llm_chain.dart, packages/langchain/lib/src/model_io/chat_models/base.dart, packages/langchain/lib/src/model_io/language_models/base.dart, packages/langchain/lib/src/model_io/llms/base.dart, packages/langchain/test/model_io/chat_models/fake_test.dart, packages/langchain_google/lib/src/chat_models/google_ai/chat_google_generative_ai.dart, packages/langchain_google/lib/src/chat_models/vertex_ai/chat_vertex_ai.dart, packages/langchain_google/lib/src/llms/vertex_ai.dart, packages/langchain_google/test/chat_models/chat_vertex_ai_test.dart, packages/langchain_google/test/llms/vertex_ai_test.dart, packages/langchain_mistralai/lib/src/chat_models/chat_mistralai.dart, packages/langchain_mistralai/test/chat_models/chat_mistralai_test.dart, packages/langchain_ollama/lib/src/chat_models/chat_ollama.dart, packages/langchain_ollama/lib/src/llms/ollama.dart, packages/langchain_ollama/test/llms/ollama_test.dart, packages/langchain_openai/lib/src/chat_models/chat_openai.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/langchain_openai/test/chat_models/anyscale_test.dart, packages/langchain_openai/test/chat_models/chat_openai_test.dart, packages/langchain_openai/test/chat_models/open_router_test.dart, packages/langchain_openai/test/llms/openai_test.dart, packages/openai_dart/test/openai_client_chat_test.dart
The following LLM/ChatModel APIs have been removed:
- `generate`
- `generatePrompt`
- `predict`
- `predictMessages`
In favour of the standard `invoke` API, part of [LangChain Expression Language](https://langchaindart.com/#/expression_language/interface).
For simple use cases that don't require composition, `call` can still be used.
=> refactor!: Remove deprecated generate and predict APIs

packages/langchain_google/lib/src/chat_models/google_ai/chat_google_generative_ai.dart, packages/langchain_google/test/chat_models/chat_google_generative_ai_test.dart
You can specify a tuned model by setting the `model` parameter to
`tunedModels/{your-model-name}`. For example:
```dart
final chatModel = ChatGoogleGenerativeAI(
defaultOptions: ChatGoogleGenerativeAIOptions(
model: 'tunedModels/my-tuned-model',
),
);
```
=> feat: Support tuned models in ChatGoogleGenerativeAI

packages/langchain_core/lib/src/chat_models/fake.dart, packages/langchain_core/lib/src/output_parsers/string.dart, packages/langchain_core/test/output_parsers/string_test.dart
When invoking this parser with `Runnable.stream`, every item from the input stream will be parsed and emitted by default. If `reduceOutputStream` is set to `true`, the parser will reduce the output stream into a single String and emit it as a single item. This is useful when the next `Runnable` in a chain expects a single String as input.
Visual example:
```
- reduceOutputStream = false
'A', 'B', 'C' -> 'A', 'B', 'C'
- reduceOutputStream = true
'A', 'B', 'C' -> 'ABC'
```
=> feat: Add reduceOutputStream option to StringOutputParser

docs/expression_language/interface.md, examples/docs_examples/bin/expression_language/interface.dart, packages/langchain/README.md, packages/langchain_core/lib/src/chains/types.dart, packages/langchain_core/lib/src/chat_models/types.dart, packages/langchain_core/lib/src/langchain/types.dart, packages/langchain_core/lib/src/language_models/types.dart, packages/langchain_core/lib/src/llms/types.dart, packages/langchain_core/lib/src/output_parsers/types.dart, packages/langchain_core/lib/src/runnables/map.dart, packages/langchain_core/lib/src/runnables/runnable.dart, packages/langchain_core/lib/src/runnables/sequence.dart, packages/langchain_core/lib/src/runnables/types.dart, packages/langchain_core/test/runnables/batch_test.dart, packages/langchain_core/test/runnables/invoke_test.dart, packages/langchain_google/lib/src/chat_models/google_ai/types.dart, packages/langchain_google/lib/src/chat_models/vertex_ai/types.dart, packages/langchain_google/lib/src/llms/vertex_ai/types.dart, packages/langchain_mistralai/lib/src/chat_models/types.dart, packages/langchain_ollama/lib/src/chat_models/types.dart, packages/langchain_ollama/lib/src/llms/types.dart, packages/langchain_openai/lib/src/chat_models/types.dart, packages/langchain_openai/lib/src/llms/mappers.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/langchain_openai/lib/src/llms/types.dart, packages/langchain_openai/test/llms/openai_test.dart
Related to #266
Batches the invocation of the `Runnable` on the given `inputs`.
```dart
final model = ChatOpenAI(apiKey: openaiApiKey);
final promptTemplate = ChatPromptTemplate.fromTemplate(
'Tell me a joke about {topic}',
);
final chain = promptTemplate | model | StringOutputParser();
final res = await chain.batch([
{'topic': 'bears'},
{'topic': 'cats'},
]);
print(res);
//['Why did the bear break up with his girlfriend? Because she was too "grizzly" for him!',
// 'Why was the cat sitting on the computer? Because it wanted to keep an eye on the mouse!']
```
If the underlying provider supports batching, this method will try to batch the calls to the provider. Otherwise, it will just call `invoke` on each input concurrently. You can configure the concurrency limit by setting the …
=> feat: Implement .batch support

docs/modules/memory/memory.md, docs/modules/model_io/models/llms/how_to/fake_llm.md, examples/browser_summarizer/pubspec.lock, examples/docs_examples/pubspec.lock, examples/hello_world_backend/pubspec.lock, examples/hello_world_cli/pubspec.lock, examples/hello_world_flutter/pubspec.lock, packages/langchain/example/langchain_example.dart, packages/langchain/test/chains/base_test.dart, packages/langchain/test/chains/combine_documents/map_reduce_test.dart, packages/langchain/test/chains/combine_documents/reduce_test.dart, packages/langchain_core/lib/src/chat_models/base.dart, packages/langchain_core/lib/src/chat_models/types.dart, packages/langchain_core/lib/src/language_models/base.dart, packages/langchain_core/lib/src/llms/base.dart, packages/langchain_core/lib/src/llms/fake.dart, packages/langchain_core/lib/src/llms/types.dart, packages/langchain_core/lib/src/prompts/base_prompt.dart, packages/langchain_core/lib/src/prompts/types.dart, packages/langchain_core/lib/src/retrievers/base.dart, packages/langchain_core/lib/src/runnables/map.dart, packages/langchain_core/lib/src/tools/base.dart, packages/langchain_core/lib/src/utils/reduce.dart, packages/langchain_core/pubspec.yaml, packages/langchain_core/test/chains/llm_chain_test.dart, packages/langchain_core/test/runnables/batch_test.dart, packages/langchain_core/test/runnables/router_test.dart, packages/langchain_core/test/runnables/stream_test.dart
Previously, the following components processed each chunk of an input stream individually, making it difficult to implement streaming chains. Now these components reduce the input stream to a single value before processing it.
- `PromptTemplate`
- `ChatPromptTemplate`
- `LLM`
- `ChatModel`
- `Retriever`
- `Tool`
=> feat: Reduce input stream for PromptTemplate, LLM, ChatModel, Retriever and Tool

packages/langchain_core/lib/src/output_parsers/json.dart, packages/langchain_core/lib/src/output_parsers/output_parsers.dart, packages/langchain_core/lib/src/output_parsers/string.dart, packages/langchain_core/test/output_parsers/json_test.dart
Example:
```dart
final model = ChatOpenAI(
apiKey: openAiApiKey,
defaultOptions: const ChatOpenAIOptions(
responseFormat: ChatOpenAIResponseFormat(
type: ChatOpenAIResponseFormatType.jsonObject,
),
),
);
final parser = JsonOutputParser<ChatResult>();
final chain = model.pipe(parser);
final stream = chain.stream(
PromptValue.string(
'Output a list of the countries france, spain and japan and their '
'populations in JSON format. Use a dict with an outer key of '
'"countries" which contains a list of countries. '
'Each country should have the key "name" and "population"',
),
);
await stream.forEach((final chunk) => print('$chunk|'));
// {}|
// {countries: []}|
// {countries: [{}]}|
// {countries: [{name: }]}|
// {countries: [{name: France}]}|
// {countries: [{name: France, population: …
```
=> feat: Add support for JsonOutputParser

packages/langchain_core/lib/src/runnables/function.dart, packages/langchain_core/lib/src/runnables/runnable.dart, packages/langchain_core/test/runnables/function_test.dart
It is common to need to map the output value of a previous runnable to a new value that conforms to the input requirements of the next runnable. `Runnable.mapInput`, `Runnable.mapInputStream`, `Runnable.getItemFromMap`, and `Runnable.getMapFromInput` are the easiest way to do that with minimal boilerplate. However, sometimes you may need more control over the input and output values. This is where `Runnable.fromFunction` comes in.
The main differences between `Runnable.mapInput` and `Runnable.fromFunction` are:
- `Runnable.fromFunction` allows you to define separate logic for invoke vs stream.
- `Runnable.fromFunction` allows you to access the invocation options.
In the following example, we use `Runnable.fromFunction` to log the output value of the previous `Runnable`. Note that we have …
=> feat!: Support different logic for streaming in RunnableFunction

packages/langchain_core/lib/src/chat_models/types.dart, packages/langchain_core/lib/src/language_models/types.dart, packages/langchain_core/lib/src/llms/types.dart, packages/langchain_openai/lib/src/chat_models/chat_openai.dart, packages/langchain_openai/lib/src/chat_models/mappers.dart, packages/langchain_openai/lib/src/llms/mappers.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/langchain_openai/test/chat_models/chat_openai_test.dart, packages/langchain_openai/test/llms/openai_test.dart
```dart
final promptTemplate = ChatPromptTemplate.fromTemplates(const [
(ChatMessageType.system, 'You are a helpful assistant that replies only with numbers in order without any spaces or commas'),
(ChatMessageType.human, 'List the numbers from 1 to {max_num}'),
]);
final chat = ChatOpenAI(apiKey: openaiApiKey);
final chain = promptTemplate.pipe(chat);
ChatResult? result;
final stream = chain.stream({'max_num': '9'});
await for (final ChatResult res in stream) {
result = result?.concat(res) ?? res;
}
expect(result!.output.content, contains('123456789'));
expect(result.usage.promptTokens, greaterThan(0));
expect(result.usage.responseTokens, greaterThan(0));
expect(result.usage.totalTokens, greaterThan(0));
```
=> feat: Include usage stats when streaming with OpenAI and ChatOpenAI

docs/modules/model_io/models/chat_models/integrations/googleai.md, docs/modules/retrieval/text_embedding/integrations/google_ai.md, examples/browser_summarizer/pubspec.lock, examples/docs_examples/bin/modules/model_io/models/chat_models/integrations/googleai.dart, examples/docs_examples/pubspec.lock, examples/docs_examples/pubspec_overrides.yaml, examples/hello_world_backend/pubspec.lock, examples/hello_world_cli/pubspec.lock, examples/hello_world_flutter/pubspec.lock, melos.yaml, packages/googleai_dart/README.md, packages/googleai_dart/lib/src/client.dart, packages/langchain_google/lib/src/chat_models/google_ai/chat_google_generative_ai.dart, packages/langchain_google/lib/src/chat_models/google_ai/mappers.dart, packages/langchain_google/lib/src/chat_models/google_ai/types.dart, packages/langchain_google/lib/src/embeddings/google_ai/google_ai_embeddings.dart, packages/langchain_google/lib/src/utils/https_client/http_client.dart, packages/langchain_google/lib/src/utils/https_client/http_client_html.dart, packages/langchain_google/lib/src/utils/https_client/http_client_io.dart, packages/langchain_google/lib/src/utils/https_client/http_client_stub.dart, packages/langchain_google/pubspec.yaml, packages/langchain_google/pubspec_overrides.yaml, packages/langchain_google/test/chat_models/google_ai/chat_google_generative_ai_test.dart, packages/langchain_google/test/embeddings/google_ai/google_ai_embeddings_test.dart
Resolves #332
This PR migrates the internal Gemini API client used by `ChatGoogleGenerativeAI` and `GoogleGenerativeAIEmbeddings` from [`googleai_dart`](https://pub.dev/packages/googleai_dart) to the official [`google_generative_ai`](https://pub.dev/packages/google_generative_ai).
**Main changes:**
- `ChatGoogleGenerativeAI` and `GoogleGenerativeAIEmbeddings` now use the version `v1beta` of the Gemini API (instead of `v1`).
- `ChatGoogleGenerativeAI` now supports `gemini-1.5-pro-latest` model
- Some categories from `ChatGoogleGenerativeAISafetySettingCategory` have been removed as they are not used anymore by the latest models 
* see https://github.com/google-gemini/generative-ai-dart/pull/150
- `GoogleGenerativeAIEmbeddings.dimensions` is currently ignored as it is not yet supported by …
=> feat!: Migrate internal client from googleai_dart to google_generative_ai

packages/ollama_dart/example/ollama_dart_example.dart, packages/ollama_dart/lib/src/generated/schema/done_reason.dart, packages/ollama_dart/lib/src/generated/schema/generate_chat_completion_response.dart, packages/ollama_dart/lib/src/generated/schema/schema.dart, packages/ollama_dart/lib/src/generated/schema/schema.freezed.dart, packages/ollama_dart/lib/src/generated/schema/schema.g.dart, packages/ollama_dart/oas/ollama-curated.yaml, packages/ollama_dart/test/ollama_dart_chat_test.dart
```dart
final res = await client.generateChatCompletion(...);
print(res.doneReason);
```
- `DoneReason.stop` - The generation hit a stop token.
- `DoneReason.length` - The maximum num_tokens was reached.
- `DoneReason.load` - The request was sent with an empty body to load the model.
=> feat: Add support for done reason in ollama_dart

packages/langchain_ollama/lib/src/chat_models/mappers.dart, packages/langchain_ollama/test/chat_models/chat_ollama_test.dart, packages/langchain_ollama/test/embeddings/ollama_test.dart, packages/langchain_ollama/test/llms/ollama_test.dart, packages/ollama_dart/test/ollama_dart_models_test.dart
```dart
final chatModel = ChatOllama(...);
final res = await chatModel.invoke(....);
print(res.finishReason);
```
- `FinishReason.stop`: The generation hit a stop token or sequence.
- `FinishReason.length`: The maximum number of tokens was reached (when setting `ChatOllamaOptions(numPredict: {maxToken}`)
=> feat: Handle finish reason in ChatOllama

packages/openai_dart/lib/openai_dart.dart, packages/openai_dart/lib/src/generated/schema/create_vector_store_request.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/pubspec.yaml
Ref: https://discord.com/channels/1123158322812555295/1243516680282439773/1243516680282439773
=> fix: Make vector store name optional in openai_dart

docs/modules/model_io/models/chat_models/integrations/open_router.md, examples/docs_examples/bin/modules/model_io/models/chat_models/integrations/open_router.dart, packages/langchain_openai/test/chat_models/open_router_test.dart
https://openrouter.ai/docs#tool-calls
=> docs: Document tool calling with OpenRouter

packages/langchain_core/lib/src/runnables/binding.dart, packages/langchain_core/lib/src/runnables/map.dart, packages/langchain_core/lib/src/runnables/runnable.dart, packages/langchain_core/lib/src/runnables/sequence.dart, packages/langchain_google/lib/src/chat_models/google_ai/chat_google_generative_ai.dart, packages/langchain_mistralai/lib/src/chat_models/chat_mistralai.dart, packages/langchain_ollama/lib/src/chat_models/chat_ollama.dart, packages/langchain_ollama/lib/src/llms/ollama.dart, packages/langchain_openai/lib/src/chat_models/chat_openai.dart, packages/langchain_openai/lib/src/llms/openai.dart, packages/langchain_openai/lib/src/tools/dall_e.dart, packages/langchain_openai/test/chat_models/open_router_test.dart
Previously only LLMs and ChatModels had a `close` method to close the associated client, but it was not a standard interface. Now the `close` method is part of the Runnable interface, so you can close any Runnable.
For example:
```dart
final chain = promptTemplate
.pipe(model)
.pipe(outputParser);
// ...
chain.close();
```
This will call the close method of all the runnables in the chain. In this case, it won't do anything for `promptTemplate` and `outputParser` as they have no associated resources to close, but it will close the HTTP client of the model.
=> feat: Add Runnable.close() to close any resources associated with it

docs/modules/model_io/models/chat_models/integrations/firebase_vertex_ai.md, packages/langchain_firebase/example/lib/main.dart, packages/langchain_firebase/example/web/flutter_bootstrap.js, packages/langchain_firebase/example/web/index.html, packages/langchain_firebase/lib/src/chat_models/vertex_ai/chat_firebase_vertex_ai.dart, packages/langchain_firebase/lib/src/chat_models/vertex_ai/types.dart
The default models has been updated from `gemini-1.0-pro` to `gemini-1.5-flash`
=> feat!: Update ChatFirebaseVertexAI default model to  gemini-1.5-flash

melos.yaml, packages/langchain_firebase/lib/src/chat_models/vertex_ai/chat_firebase_vertex_ai.dart, packages/langchain_firebase/lib/src/chat_models/vertex_ai/mappers.dart, packages/langchain_firebase/pubspec.lock, packages/langchain_firebase/pubspec.yaml
You can now specify the Firebase Auth instance to use for your VertexAI requests.
Ref: https://github.com/firebase/flutterfire/pull/12797
=> feat: Add support for Firebase Auth in ChatFirebaseVertexAI

docs/modules/model_io/models/chat_models/integrations/googleai.md, packages/langchain_firebase/lib/src/chat_models/vertex_ai/chat_firebase_vertex_ai.dart, packages/langchain_google/lib/src/chat_models/google_ai/chat_google_generative_ai.dart, packages/langchain_google/lib/src/chat_models/google_ai/types.dart
The default models has been updated from `gemini-1.0-pro` to `gemini-1.5-flash`
=> feat!: Update ChatGoogleGenerativeAI default model to  gemini-1.5-flash

packages/langchain_core/lib/src/chat_models/types.dart, packages/langchain_core/lib/src/language_models/types.dart, packages/langchain_firebase/lib/src/chat_models/vertex_ai/mappers.dart, packages/langchain_google/lib/src/chat_models/google_ai/mappers.dart, packages/langchain_openai/lib/src/chat_models/mappers.dart
Use `ChatToolChoice.required` to force the model to call at least one tool (but without forcing a particular tool).
=> feat: Add support for ChatToolChoiceRequired

packages/langchain_openai/lib/src/chat_models/chat_openai.dart, packages/langchain_openai/lib/src/chat_models/types.dart
Whether to enable parallel tool calling during tool use. By default, it is enabled.
Ref: https://platform.openai.com/docs/guides/function-calling/parallel-function-calling
=> feat: Add support for disabling parallel tool calls in ChatOpenAI

packages/openai_dart/lib/src/generated/schema/create_chat_completion_request.dart, packages/openai_dart/lib/src/generated/schema/create_chat_completion_response.dart, packages/openai_dart/lib/src/generated/schema/create_chat_completion_stream_response.dart, packages/openai_dart/lib/src/generated/schema/schema.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/lib/src/generated/schema/service_tier.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/oas/openapi_official.yaml, packages/openai_dart/pubspec.yaml
Specifies the latency tier to use for processing the request. This parameter is relevant for customers subscribed to the scale tier service:
- If set to 'auto', the system will utilize scale tier credits until they are exhausted.
- If set to 'default', the request will be processed using the default service tier with a lower uptime SLA and no latency guarantee.
When this parameter is set, the response body will include the `service_tier` utilized.
=> feat: Add support for service tier in openai_dart

packages/langchain_openai/lib/src/chat_models/chat_openai.dart, packages/langchain_openai/lib/src/chat_models/mappers.dart, packages/langchain_openai/lib/src/chat_models/types.dart
Specifies the latency tier to use for processing the request. This parameter is relevant for customers subscribed to the scale tier service:
- If set to 'auto', the system will utilize scale tier credits until they are exhausted.
- If set to 'default', the request will be processed using the default service tier with a lower uptime SLA and no latency guarantee.
When this parameter is set, the response body will include the `service_tier` utilized.
=> feat: Add support for service tier in ChatOpenAI

packages/langchain_openai/lib/src/chat_models/chat_openai.dart
`OpenAI-Beta` header is only required if you use OpenAI beta features (like the Assistant API). `ChatOpenAI` doesn't use any beta API. However `OpenAIClient` adds this header by default, which seems to cause issues with some OpenAI compatible APIs (like [OpenRouter](https://github.com/davidmigloz/langchain_dart/issues/510)).
=> refactor: Don't send OpenAI-Beta header in ChatOpenAI

docs/expression_language/primitives/mapper.md, docs/expression_language/streaming.md, docs/modules/model_io/models/chat_models/integrations/openai.md, docs/modules/model_io/output_parsers/json.md, examples/docs_examples/bin/expression_language/cookbook/streaming.dart, examples/docs_examples/bin/expression_language/primitives/mapper.dart, examples/docs_examples/bin/modules/model_io/models/chat_models/integrations/openai.dart, examples/docs_examples/bin/modules/model_io/output_parsers/json.dart, packages/langchain_openai/lib/src/chat_models/mappers.dart, packages/langchain_openai/lib/src/chat_models/types.dart, packages/langchain_openai/test/chat_models/chat_openai_test.dart
[Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs) is a feature that ensures the model will always generate responses that adhere to your supplied JSON Schema, so you don't need to worry about the model omitting a required key, or hallucinating an invalid enum value.
```dart
final prompt = PromptValue.chat([
ChatMessage.system(
'Extract the data of any companies mentioned in the '
'following statement. Return a JSON list.',
),
ChatMessage.humanText(
'Google was founded in the USA, while Deepmind was founded in the UK',
),
]);
final chatModel = ChatOpenAI(
defaultOptions: ChatOpenAIOptions(
model: 'gpt-4o',
temperature: 0,
responseFormat: ChatOpenAIResponseFormat.jsonSchema(
ChatOpenAIJsonSchema(
name: 'Companies',
description: 'A list of …
```
=> feat: Add support for Structured Outputs in ChatOpenAI

packages/langchain_openai/lib/src/chat_models/types.dart, packages/openai_dart/lib/src/generated/schema/create_chat_completion_request.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/oas/openapi_official.yaml
> `chatgpt-4o-latest` model version continuously points to the version of GPT-4o used in [ChatGPT](https://chatgpt.com/), and is updated frequently. 
>
> We are releasing this model for developers and researchers to explore OpenAI's latest research. For production use, OpenAI recommends using dated GPT models, which are optimized for API usage.
=> feat: Add chatgpt-4o-latest to model catalog

packages/langchain_openai/lib/src/chat_models/chat_openai.dart, packages/langchain_openai/lib/src/chat_models/mappers.dart, packages/langchain_openai/lib/src/chat_models/types.dart
When the Structured Outputs API returns a refusal, a `OpenAIRefusalException` will be thrown.
More info: https://platform.openai.com/docs/guides/structured-outputs/refusals
=> feat: Handle refusal in OpenAI's Structured Outputs API

packages/langchain_openai/lib/src/chat_models/mappers.dart
Include log probability information for the generation (`result.metadata.logprobs`).
- token: The token.
- logprob:  The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.
- bytes: A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.
required List<int>? bytes,
- topLogprobs:  List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested …
=> feat: Include logprobs in result metadata from ChatOpenAI

packages/langchain_core/lib/src/tools/base.dart, packages/langchain_core/lib/src/tools/string.dart
When defining your tool, set the `strict` parameter to true to enable strict schema adherence when generating the tool call. If set to true, the model will follow the exact schema defined in the `inputJsonSchema` field.
This is only supported by OpenAI provider at the moment.  And they only support [a subset of JSON Schema](https://platform.openai.com/docs/guides/structured-outputs/supported-schemas) is supported when strict is enabled. Check out [their docs](https://platform.openai.com/docs/guides/structured-outputs) for more info.
=> feat: Support OpenAI's strict mode for tool calling in ChatOpenAI

docs/modules/retrieval/vector_stores/integrations/objectbox.md, packages/langchain_community/lib/src/vector_stores/objectbox/base_objectbox.dart, packages/langchain_community/lib/src/vector_stores/objectbox/objectbox.dart, packages/langchain_community/test/vector_stores/objectbox/objectbox_test.dart, packages/langchain_core/lib/src/vector_stores/base.dart
You can now use `ObjectBoxVectorStore.deleteWhere` to delete documents based on a condition.
```dart
await vectorStore.deleteWhere(
ObjectBoxDocumentProps.metadata.contains('cat'),
);
=> feat: Add support for deleteWhere in ObjectBoxVectorStore

packages/langchain_community/lib/src/vector_stores/objectbox/base_objectbox_stub.dart, packages/langchain_community/lib/src/vector_stores/objectbox/ob.dart, packages/langchain_community/lib/src/vector_stores/objectbox/ob_io.dart, packages/langchain_community/lib/src/vector_stores/objectbox/ob_stub.dart, packages/langchain_community/lib/src/vector_stores/objectbox/objectbox_stub.dart, packages/langchain_community/lib/src/vector_stores/objectbox/types_stub.dart, packages/langchain_community/lib/src/vector_stores/vector_stores.dart
The langchain_community package is currently displayed as if it doesn't support web.
This is due to the ObjectBox integration, whose package doesn't support web. 
This PR adds web stubs for all classes related to the ObjectBox integration.
=> refactor: Add stubs for ObjectBox on web platform

packages/langchain_openai/lib/src/chat_models/mappers.dart
`maxTokens` is deprecated in favor of `maxCompletionTokens` in the OpenAI API, and is not compatible with [o1 series models](https://platform.openai.com/docs/guides/reasoning).
=> refactor: Migrate ChatOpenAI to maxCompletionTokens

docs/modules/model_io/models/chat_models/integrations/googleai.md, examples/docs_examples/bin/modules/model_io/models/chat_models/integrations/googleai.dart, examples/docs_examples/pubspec.lock, examples/hello_world_flutter/pubspec.lock, melos.yaml, packages/langchain_google/lib/src/chat_models/google_ai/chat_google_generative_ai.dart, packages/langchain_google/lib/src/chat_models/google_ai/mappers.dart, packages/langchain_google/lib/src/chat_models/google_ai/types.dart, packages/langchain_google/pubspec.yaml, packages/langchain_google/test/chat_models/google_ai/chat_google_generative_ai_test.dart
https://ai.google.dev/gemini-api/docs/code-execution
=> feat: Add support for code execution in ChatGoogleGenerativeAI

packages/openai_realtime_dart/lib/src/api.dart, packages/openai_realtime_dart/lib/src/client.dart, packages/openai_realtime_dart/lib/src/conversation.dart, packages/openai_realtime_dart/test/client_test.dart
Fixes for using openai realtime api. Tool calling is not working in current library version, this imp fixes it, additionally, receiving user role messages was triggering an exception.
=> Fixes Openai realtime implementation, fixing tool usage in particular.

packages/openai_dart/lib/src/client.dart
- Description: `submitThreadToolOutputsToRunStream` was not returning any events.
- Issue: (same as description)
- Dependencies: None.
- Tag maintainer: @davidmigloz
=> OpenAI: Fix submitThreadToolOutputsToRunStream

packages/langchain_community/lib/src/document_loaders/web.dart
- Description: Document loader returns weird characters in some languages.
Sample article: http://web.tccf.org.tw/lib/addon.php?act=post&id=4975
Sample screenshot: 
- General: @davidmigloz
=> fix: Character support on web loader

packages/openai_realtime_dart/README.md, packages/openai_realtime_dart/example/openai_realtime_dart_example.dart, packages/openai_realtime_dart/lib/src/api.dart, packages/openai_realtime_dart/lib/src/client.dart, packages/openai_realtime_dart/lib/src/utils.dart, packages/openai_realtime_dart/test/api_test.dart, packages/openai_realtime_dart/test/client_test.dart
```dart
final client = RealtimeClient(
apiKey: Platform.environment['OPENAI_API_KEY'],
);
await client.connect(model: 'gpt-4o-mini-realtime-preview');
```
=> feat: Allow to pass a custom model in OpenAI RealtimeClient

melos.yaml, packages/langchain_firebase/example/pubspec.lock, packages/langchain_firebase/lib/src/chat_models/vertex_ai/chat_firebase_vertex_ai.dart, packages/langchain_firebase/lib/src/chat_models/vertex_ai/mappers.dart, packages/langchain_firebase/lib/src/chat_models/vertex_ai/types.dart, packages/langchain_firebase/pubspec.lock, packages/langchain_firebase/pubspec.yaml
Fixed some breaking changes they introduced in [the first stable release](https://pub.dev/packages/firebase_vertexai/changelog#100).
Now you can provide a `responseSchema` for structured outputs:
```dart
final options = ChatFirebaseVertexAIOptions(
//...
responseSchema: {
'type': 'object',
'properties': {
'answer': {
'type': 'string',
'description': 'The answer to the question being asked',
},
'sources': {
'type': 'array',
'items': {'type': 'string'},
'description': 'The sources used to answer the question',
},
},
'required': ['answer', 'sources'],
},
);
```
=> feat: Support responseSchema in ChatFirebaseVertexAI

packages/openai_realtime_dart/lib/src/client.dart
Resolves #696
- prevent infinite tool invocation when session `toolChoice` is `required`
- allow passing optional `ResponseConfig` to `createResponse`
=> fix: toolChoice required infinite loop in openai_realtime_dart

packages/openai_dart/lib/src/generated/schema/create_chat_completion_request.dart, packages/openai_dart/lib/src/generated/schema/schema.dart, packages/openai_dart/lib/src/generated/schema/schema.freezed.dart, packages/openai_dart/lib/src/generated/schema/schema.g.dart, packages/openai_dart/lib/src/generated/schema/verbosity.dart, packages/openai_dart/oas/openapi_curated.yaml, packages/openai_dart/test/openai_client_chat_test.dart
Verbosity determines how many output tokens are generated. Lowering the number of tokens reduces overall latency. While the model's reasoning approach stays mostly the same, the model finds ways to answer more concisely—which can either improve or diminish answer quality, depending on your use case. Here are some scenarios for both ends of the verbosity spectrum:
*   **High verbosity:** Use when you need the model to provide thorough explanations of documents or perform extensive code refactoring.
*   **Low verbosity:** Best for situations where you want concise answers or simple code generation, such as SQL queries.
Models before GPT-5 have used `medium` verbosity by default. With GPT-5, we make this option configurable as one of `high`, `medium`, or `low`.
When generating code, `medium` …
=> feat: Add Verbosity support in openai_dart

packages/langchain/lib/src/chains/combine_documents/reduce.dart, packages/langchain_core/lib/src/prompts/template.dart, packages/langchain_core/lib/src/utils/reduce.dart, packages/langchain_openai/lib/src/chat_models/mappers.dart, packages/langchain_openai/lib/src/chat_models/types.dart
New fields in `ChatOpenAIOptions`:
```dart
/// Whether or not to store the output of this chat completion request.
///
/// See https://platform.openai.com/docs/api-reference/chat/create#chat-create-store
final bool? store;
/// Constrains effort on reasoning for reasoning models.
/// Supported values are `minimal`, `low`, `medium`, and `high`.
///
/// See https://platform.openai.com/docs/api-reference/chat/create#chat-create-reasoning_effort
final ChatOpenAIReasoningEffort? reasoningEffort;
/// Developer-defined tags and values used for filtering completions.
///
/// See https://platform.openai.com/docs/api-reference/chat/create#chat-create-metadata
final Map<String, String>? metadata;
/// Whether to return log probabilities of the output tokens.
///
/// See …
```
=> feat: Support reasoningEffort, verbosity and other new fields in ChatOpenAI
